### ISSUE TITLE
Faster modular reduction for Falcon prime

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#1005]
During the Falcon DSA signature verification, the Falcon prime $q = 12289$ is much smaller than the Miden VM native prime $Q := 2^{64} - 2^{32} +1$. 
This can be used in order to avoid 64-bit modular reductions. The best scenario would've been substituting `% q` with just a `u32` modular division which is very efficient in Miden VM. Unfortunately, the coefficients that the `% q`  operation are applied to are not necessarily in the range $[0, 2^{32} - 1]$ but are only guaranteed to be in $[0, \delta]$ where $\delta := 1025 * q^2$.

Now, noticing that $1025 * q < 2^{32} - 1$, we can use non-determinism to reduce a number in the range $[0, 1025 * q^2]$ modulo $q$  as follows:
1. The VM non-determinisitcally gets two field elements $x$ and $y$ that are the claimed  to represent the quotient of $a$ by $q$ and remainder of $a$ by $q$, respectively.
2. The program then goes on to verify that:
   1.  $a = x * q + y$
   2.  $x < 1025 * q$
   3.  $y < q$

This will bring down the cost of `% q` in the context of Falcon verification from the current $38$ cycles to $19$ cycles.

**Comment by bobbinth** [comment]
A couple of quick questions:

1. What is the estimated impact of this change on the overall verification procedure? (e.g., will it make it 10% faster, 30% faster etc.?).
2. Do you already have the procedure that takes 19 cycles written out?

**Comment by Al-Kindi-0** [comment]
>     1. What is the estimated impact of this change on the overall verification procedure? (e.g., will it make it 10% faster, 30% faster etc.?).
> 
I wrote down but can't find it within the present notes. I tried to write it from scratch again but I am getting a worst count than 19 i.e., 25 cycles. Either I messed up the count above or I diverged from the implementation I had written down.
Here is my attempt:
```
adv_push.2  
#=>[x, y, a, ...] where a = x * q + y  (2 cycles)

# Check x < 1025 * q
dup
push.CST 
u32checked_lt           #(8 cycles)

# Compute q * x 
push.Q mul
#=> [x*q, y, a, ...]    #(2 cycles)

# Check y < q 
dup.1
push.Q
u32checked_lt           #(8 cycles)


# Add y to x * q
dup.1 add
#=> [x*q + y, y, a, ...]        (2 cycles)

# Assert a = x * q + y 
movup.2 assert_eq
#=> [y, ...]                    (3 cycles)
```

>     2. Do you already have the procedure that takes 19 cycles written out?
I have actually missed a crucial point. The above improvement proposal assumed that the `hash_to_point` algorithm outputs coefficients of a polynomial that are smaller than `q`. After the simplification we introduced by removing the rejection sampling, we could now avoid reducing the coefficients. This means that the above bound $< 1025 * q^2$ is no longer satisfied and thus we need to come up with a new approach.
I did a rough estimation on the potential gain and I can see that we are calling `poly512::mod_12289` 4 times. So assuming that the above solution were to be correct, the savings would be `128 * 4 * 14` where 128 is the number of iteration of a loop, 4 is the number of `mod_12289` and 14 is `39-25`.

**Comment by Al-Kindi-0** [comment]
Actually, I think there is a modular reduction that is missing. This is the one that turns the output of RPO in the hash-to-point algorithm into a field element in the Falcon field. The extra modular reduction using `poly512::mod_12289` should be placed [here](https://github.com/0xPolygonMiden/miden-vm/blob/ac138537587dc7bae9d2e5835d6f5f6381937ec7/stdlib/asm/crypto/dsa/falcon.masm#L401) in order to make the argument in that procedure work.

**Comment by Al-Kindi-0** [comment]
Actually the situation is a bit more complicated than the above. Here is a short summary:
The previous hash-to-point algorithm produced elements that were less than $2^{16}$ and thus this line [here](https://github.com/0xPolygonMiden/miden-vm/blob/ac138537587dc7bae9d2e5835d6f5f6381937ec7/stdlib/asm/crypto/dsa/falcon.masm#L401) was guaranteed to not overflow (`v` is one of the outputs of the hash-to-point procedure). With the new hash-to-point algorithm, the outputs now are field elements, hence that line can overflow and the argument underlying `proc.diff_mod_q` is not applicable anymore. This means that the outputs of the new hash-to-point algorithm need to be reduced modulo the Falcon prime in order to insure no-overflow (or the whole argument should be updated). Unfortunately, this means that although the new hash-to-point algorithm reduces the cycle count from 18000 to 1800, it requires 512 modular reductions (i.e., one per coefficient) which is 512 * 39 which is approximately 20000 cycles.
Conclusion: We might need to revert to the old hash-to-point algorithm.

**Comment by Al-Kindi-0** [comment]
Having settled on the new hash-to-point algorithm, the current issue is now superseded by #1088
