### ISSUE TITLE
Finish tiered Sparse Merkle Tree

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-vm#1028]
Maybe a copy, but I couldn't find an issue about that

**Comment by bobbinth** [comment]
Duplicate of #258 which was closed by https://github.com/0xPolygonMiden/miden-vm/pull/1046, https://github.com/0xPolygonMiden/miden-vm/issues/1048, https://github.com/0xPolygonMiden/miden-vm/pull/1036 and other related PRs.
