### ISSUE TITLE
Memoization of hash execution traces

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#103]
Currently, [Hasher](https://github.com/maticnetwork/miden/blob/next/processor/src/hasher/mod.rs) component of the processor always builds traces for hash computations from scratch. This happens even in cases when computing hashes of the same values more than once.

We can improve on this by keeping track of the hashes which have already been computed, and just copying the sections of the trace with minimal modifications. Specifically, the only thing that needs to be updated when computing hash for previously hashed values is the row address column of the trace - everything else would remain the same.

This can also be done at a higher level. For example, we could keep track of sections of a trace used for Merkle path verification and then, if the same Merkle path was verified more than once, we can just copy the relevant sections of the trace (again, with minimal modifications).

**Comment by willyrgf** [comment]
I would love to work in this issue if no one is.

**Comment by bobbinth** [comment]
@willyrgf - thank you for asking! I'd like to hold off on this specific issue for now. Some things we are working on now (e.g., decoder) may affect this and I think it makes sense to tackle this after these components are complete.

**Comment by willyrgf** [comment]
It's ok, I'll keep looking.

**Comment by willyrgf** [comment]
Maybe it would be interesting to have a label like `blocked` or `stale` for these cases.

**Comment by vlopes11** [comment]
Upd for future ref: hasher was moved to chiplets
https://github.com/maticnetwork/miden/blob/fb4df53942d36c2348ca926070a224fb37f18c57/processor/src/chiplets/hasher/mod.rs

**Comment by tohrnii** [comment]
Moved to #606.
