### ISSUE TITLE
Support to convert binary MASM to text

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#1040]
Currently we have a [`to_bytes`](https://github.com/0xPolygonMiden/miden-vm/blob/105ee9e241fafeac97fbcd14861b2eaed5548e1e/assembly/src/ast/mod.rs#L213) implementation, but we don't seem to have an equivalent `to_text` implementation. The `to_text` would be nice to have while encoding an account to a human readable format.

**Comment by bobbinth** [comment]
We do have `Display` implemented on `ProgramAst` (see [here](https://github.com/0xPolygonMiden/miden-vm/blob/next/assembly/src/ast/mod.rs#L340)). Maybe this will work?
