### ISSUE TITLE
Implement `smt_peek` decorator 

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#1045]
Add `adv.smt_peek` decorator (this would complement the existing `adv.smt_get` and `adv.smt_insert` decorators). The decorator could work as follows:
```
Inputs:
  Operand stack: [KEY, ROOT, ...]
  Advice stack:  [...]

Outputs:
  Operand stack: [KEY, ROOT, ...]
  Advice stack:  [VALUE, ...]
```
Where `VALUE` is the value associated with the `KEY` in the TSMT with the specified `ROOT`.

**Comment by bobbinth** [comment]
Closed by #1056.
