### ISSUE TITLE
Implement `Debug` and `Display` on `TraceLenSummary`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#1047]
When inspecting the `TraceLenSummary` it is typical that a user would want to print the trace length summary to inspect the trace length information.  To support this we should implement `Debug` and `Display` on `TraceLenSummary`.

**Comment by bobbinth** [comment]
Agree with implementing `Debug` but I wonder if this struct is "too complex" for implementing `Display`. Specifically, we can't the data on a single line (or at least it won't look good), and so, we'd have to make an opinionated choice on how to print it out (e.g., as a simple list, or a table, or something else).

**Comment by frisitano** [comment]
Good point.  I think `Debug` is sufficient for now if we don't want to make opinionated decisions about how to implement `Display`.

**Comment by bobbinth** [comment]
Closed by #1058.
