### ISSUE TITLE
Integrate Falcon DSA into Miden VM

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#1048]
As the Falcon DSA is practically done #1000, we need to add some support for it to be useful. Things are still not clear but I think that we should think about supporting the following flow:

1. Given as input, via the operand stack, a digest of a public key `PK` and a digest of a message `MSG`, the VM receives via the advice provider the pre-image of `PK`, which is the coefficients of a polynomial `h`.
2. A signature composed of a nonce `NONCE` and a signature represented as a polynomial `s2`, also via the advice provider.
3. A polynomial `pi` representing the product of `h` and `s2` in $\mathbb{Z}_Q[x]$ where $Q$ is the Miden prime.

The MASM code implementing the verification procedure will then go one to:

1. Check that `h` hashes to `PK`.
2. Compute the polynomial `c` that is the hash-to-point of `NONCE || MSG` using RPO.
3. Check that `pi` is indeed the product of `h` and `s2` in $\mathbb{Z}_Q[x]$.

The main question, I believe, is how to accommodate the above flow using the current infrastructure or whether there is a need for something more.

**Comment by Al-Kindi-0** [comment]
Makes sense!
One thing that is still not clear to me is how would the scenario where the VM requests a signature from a 3rd party work in the above.

**Comment by bobbinth** [comment]
I was thinking that in such cases we'd need to provide a specialized implementation of the advice provider which overrides the `sign` (or `falcon_sign`) method.

For example, let's say we are implementing a wallet which needs to make a call to some external component (via an RPC or something else) to generate a signature. We'd create a new `AdviceProvider` implementation in which we'd replace the default implementation of `sign` with an implementation which makes a call to this external component according to the interfaces this component exposes.

**Comment by Al-Kindi-0** [comment]
That clarifies things, thank you!

**Comment by bobbinth** [comment]
Closed by #1068.
