### ISSUE TITLE
Consider removing unreachable code

### ISSUE THREAD

**Issue by saxenism** [0xPolygonMiden/miden-vm#1066]
I was working on PR #1062 which solves issue #843 and while doing that I came across **a lot** of snippets of the **same code** that will never be executed or [unreachable code](https://en.wikipedia.org/wiki/Unreachable_code#:~:text=Unreachable%20code%20is%20sometimes%20also,the%20output%20of%20a%20program.&text=Sometimes%20an%20automated%20test%20is%20the%20only%20thing%20using%20the%20code.)

Here are a few examples:

1. [parse_push](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/ast/parsers/io_ops.rs#L29)

> Here the match case of `0` will never be executed because of the [debug_assert_equal](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/ast/parsers/io_ops.rs#L27) on the very first line.

<img width="1079" alt="Screenshot 2023-09-07 at 4 57 19 PM" src="https://github.com/0xPolygonMiden/miden-vm/assets/32522659/90857b44-c030-4806-89a5-1910367ac75d">

2. [parse_locaddr](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/ast/parsers/io_ops.rs#L64)

> Here the match case of `0` will never be executed because of the [debug_assert_equal](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/ast/parsers/io_ops.rs#L27) on the very first line.

<img width="1095" alt="Screenshot 2023-09-07 at 4 57 46 PM" src="https://github.com/0xPolygonMiden/miden-vm/assets/32522659/020b84ef-b7d0-4a94-808f-ae8a59066cc4">

Similarly, many other cases exist where nothing changes if we include the `0` case while matching or not because of the assertion about the 0th part of the token in all of these functions.

Happy to hear feedback on this.

**Comment by frisitano** [comment]
I agree that removing the branch for the match case of `0` wouldn't result in any functional changes. However, one could argue that the existence of the `0` branch expresses the fact that an operation having `0` parts is not possible and this makes the code more readable. Having said that one could also argue that this is somewhat redundant as the `debug_assert_eq!(..)` statement communicates the same message to the programmer.  With everything considered I would be in favour of keeping the `0` branch as I think it does add some value in terms of readability but I am not strongly opinionated on this and would be open to hearing the opinions of other contributors.

**Comment by saxenism** [comment]
One option could be moving the 'debug_assert_eq!(..)' into the ‘match 2’ case ?

**Comment by frisitano** [comment]
> One option could be moving the `debug_assert_eq!(..)` statement into the `match 2` case.

I think we want the `debug_assert_eq(..)` to be in the functions global scope as it applies to all branches of the match expression (including match case of 1) so I don't think this would be a beneficial change.

**Comment by bobbinth** [comment]
I'd probably keep it as is now. One of the reasons for having `0` marked as `unreachable` is to make it clear that it's not going to fall through to the default case. For example:
```Rust
pub fn parse_locaddr(op: &Token, constants: &LocalConstMap) -> Result<Node, ParsingError> {
    debug_assert_eq!(op.parts()[0], "locaddr");
    match op.num_parts() {
        0 => unreachable!(),
        1 => Err(ParsingError::missing_param(op, "locaddr.<index>")),
        2 => {
            let index = parse_param_with_constant_lookup::<u16>(op, 1, constants)?;
            Ok(Instruction(Locaddr(index)))
        }
        _ => Err(ParsingError::extra_param(op)),
    }
}
```
If we remove `0` branch, then it may look like `extra_param` error will be returned for `0` case. Not saying that it is difficult to figure out that that's not the case - but having `0` be unreachable makes it super clear and reduces cognitive load by a bit.

**Comment by frisitano** [comment]
Given that two contributors have come to the same conclusion I will go ahead and close this issue.
