### ISSUE TITLE
Documentation link in the README is broken 

### ISSUE THREAD

**Issue by MauroToscano** [0xPolygonMiden/miden-vm#1093]
Documentation link of the readme redirects to https://wiki.polygon.technology/docs/miden/intro/main/, and the website says "page not found"

**Comment by bobbinth** [comment]
We are in the process of overhauling docs on the main Polygon site. But you can always find the latest docs at these links:

- Miden VM: https://0xpolygonmiden.github.io/miden-vm/
- Miden Rollup (still WIP): https://0xpolygonmiden.github.io/miden-base/

**Comment by bobbinth** [comment]
For now, I've updated the main readme to point to https://0xpolygonmiden.github.io/miden-vm. Thank you for noticing!

**Comment by MauroToscano** [comment]
No problem! Thanks Bobbin!
