### ISSUE TITLE
Add `get_module(path)` method to the `Library` trait. 

### ISSUE THREAD

**Issue by Dominik1999** [0xPolygonMiden/miden-vm#1095]
Ideally, we should not use the path here to get the module AST. A better option would be to get it directly from `MidenLib`. We can do this right now by iterating over modules and picking the one with path `faucets/basic.masm`. But a better option would be to add `get_module(path)` metho to the `Library` trait. Let's create an issue for this in Miden VM repo.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-base/pull/263#discussion_r1346642344_

**Comment by Overcastan** [comment]
Closed by #1123.
