### ISSUE TITLE
Testing Falcon signature

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#1096]
The test coverage we currently have for the Falcon signature implementation in Miden VM is a bit lacking. The following spots need to be covered:

1. The decorators for signature verification especially failure cases.
2. The probabilistic polynomial multiplication routine.
3. The `norm_sq` procedure.
4. The `diff_mod_q` procedure (for overflow/underflow).

**Comment by Al-Kindi-0** [comment]
That would awesome! Let me know if you need any help or pointers.

**Comment by scottdieringer** [comment]
Have a PR ready: https://github.com/0xPolygonMiden/miden-vm/pull/1257

**Comment by scottdieringer** [comment]
Ready for review.

**Comment by Al-Kindi-0** [comment]
I did @scottdieringer but would be great to  wait for @bobbinth 's review as well

**Comment by bobbinth** [comment]
@scottdieringer - sorry for being so slow with the review. Will try do this today or tomorrow.

**Comment by bobbinth** [comment]
@scottdieringer - sorry for the delay on this again. We are wrapping up a [PR](https://github.com/0xPolygonMiden/crypto/pull/285) related to Falcon signature in `miden-crypto`, and it might make sense to merge the PR for this issue after we've merged the work related to that PR.

**Comment by scottdieringer** [comment]
@bobbinth I merged the miden-crypto 0.9.0 into the PR(https://github.com/0xPolygonMiden/miden-vm/pull/1257) and it's ready for review.

**Comment by bobbinth** [comment]
Closed by #1257. Thank you @scottdieringer for all your help on this!
