### ISSUE TITLE
Modifying miden-lib/asm/sat/internal/asset.masm results in compilation failures

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1097]
To reproduce

1. Add any instruction anywhere inside the file (I tested with `add`, `assertz`, and many more)
2. run `cargo test`
3. Notice most asset & note tests failing with `ScriptCompilationError(PhantomCallsNotAllowed(...))`

**Comment by bobbinth** [comment]
Closing this as the fix is specific to how we do testing in Miden base and is covered in https://github.com/0xPolygonMiden/miden-base/issues/303.
