### ISSUE TITLE
Refactor `Process` struct

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#1100]
As part of #1082, the introduction of the `Host` object and associated `ProcessState`, we had to place the `Host` object behind a `RefCell` to leverage the interior mutability pattern and defer borrow checks to runtime.  This is because we take a mutable and immutable reference of the `Process` object when invoking `Host` requests. However, we never modify any of the fields of the `Process` struct which are read as immutable.  To remove the requirement for the usage of the `RefCell` we should refactor the `Process` struct as follows:

```Rust
struct Process<H>
where
    H: Host,
{
    state: VmState,
    host: H,
    max_cycles: u32,
}
```

See this comment thread for more insight: https://github.com/0xPolygonMiden/miden-vm/pull/1082#discussion_r1344755824

**Comment by bobbinth** [comment]
Superseded by changes in #1571.
