### ISSUE TITLE
Add `emit` assembly instruction

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#1105]
With the introduction of `Host` interface in #1082, we are now able to support more robust signaling from the VM to the host. Such signals could be useful in a variety of situations - for example, to inform the host that the VM is about to perform some higher level operation (e.g., update asset vault for an account). While we can already intercept advice injector/extractor requests to the host - this approach may not be flexible enough.

To provide much more flexibility to the user, we could introduce an `emit` instruction. This instruction would work as follows:
```
emit.<event_id>
```
Where, `event_id` could be any 32-bit value.

This instruction would be backed by a decorator - maybe something like `Event(u32)`. This would also mean that emitting events would not increase VM's cycle count.

On the host side, we'll need to add an extra method to the `Host` trait - maybe something like this:
```Rust
pub trait Host {
    ...

    fn on_event<S: ProcessState>(
        &mut self,
        process: &S,
        event_id: u32,
    ) -> Result<HostResponse, ExecutionError> {
        // TODO: print out current context, cycle, and event ID
        Ok(HostResponse::None)
    }

    ...
}
```
As shown above, by default, this method would just print the event to `stdout` an return.

**Comment by frisitano** [comment]
This sounds good.  One potential extension to this could be to also allow for parameters to be passed via the decorator, e.g. `emit.<event_id>.<param_1>.(...).<param_n>`, this would then be parsed into a struct of the form:

```
pub struct Event {
    id: u32,
    params: Vec<u32>
}
```

However, I can't think of any immediate use cases in which parameters would be required so maybe we go with the simple case as described in the opening post.  To better support this intuition, I will asses our requirements of how events will be used in `miden-base` and create an issue to detail this.
