### ISSUE TITLE
Make `u32sh*` and `u32rot*` instructions always checked 

### ISSUE THREAD

**Issue by Overcastan** [0xPolygonMiden/miden-vm#1134]
It turned out that emulation of checked variants of `u32sh*` and `u32rot*` instructions could be relatively complicated and expensive. At the same time making these instructions always checked require usage of the only one additional `u32assert2` operation, what will be even cheaper in case of emulation. 

That's why we should make `u32shl`, `u32shr`, `u32rotl` and `u32rotr` operation always checked.

**Comment by bobbinth** [comment]
Closing this as we decided not to implement this functionality.
