### ISSUE TITLE
FailedAssertion error code should be displaying as integer

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#1147]
When displaying the error code associated with a failed assertion we should display it as an integer instead of a field element.

https://github.com/0xPolygonMiden/miden-vm/blob/c097af7ca53da2026cec10d9245a006b42186643/processor/src/errors.rs#L88-L90

**Comment by bobbinth** [comment]
The above code should print out `Felt` as an integer (`Display` [implementation](https://github.com/facebook/winterfell/blob/main/math/src/field/f64/mod.rs#L299) on `Felt` calls `as_int()` method). Are there some other places where it is being printed out differently?

**Comment by frisitano** [comment]
> The above code should print out `Felt` as an integer (`Display` [implementation](https://github.com/facebook/winterfell/blob/main/math/src/field/f64/mod.rs#L299) on `Felt` calls `as_int()` method). Are there some other places where it is being printed out differently?

Yes, when a program panics due to a failed `.unwrap()` the `Felt` appears to be displayed in Montgomery form. It's possible this is because it's being displayed using the `Debug` derivation.  Maybe we should implement `Debug` on `Felt` instead of this?

**Comment by bobbinth** [comment]
> Yes, when a program panics due to a failed `.unwrap()` the `Felt` appears to be displayed in Montgomery form.

Ah! Makes sense.

> It's possible this is because it's being displayed using the `Debug` derivation. Maybe we should implement `Debug` using `.as_int()` on `Felt` instead of #1148?

Yes, I think that's what's probably is going on. And yes, I think it would probably be better to print out the actual integer value for `Debug` as well (and if someone needs to print out the internal value, they can use `inner()` method).

**Comment by bobbinth** [comment]
@frisitano - since https://github.com/facebook/winterfell/pull/228 has been merged, we can probably close this issue?
