### ISSUE TITLE
`test_utils::TestError`: rely on error type equality instead of string matching

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1152]
`TestError` currently relies on [strings](https://github.com/0xPolygonMiden/miden-vm/blob/ed0e87019fd1354b782cfab9bfbe5daa183a4e16/test-utils/src/lib.rs#L74-L77) and [substring matching](https://github.com/0xPolygonMiden/miden-vm/blob/ed0e87019fd1354b782cfab9bfbe5daa183a4e16/test-utils/src/lib.rs#L135-L137) to confirm that an expected error occurred.

A better way is to use type equality on errors, which was added in https://github.com/0xPolygonMiden/miden-vm/pull/1145.

An apparent downside of the current approach is that when the `Debug` implementation of a type used in errors changes, tests break. This occurred recently with the [`Debug` implementation of fields changing](https://github.com/facebook/winterfell/pull/228), and the [`operations::sys_ops::assert_with_code` test](https://github.com/0xPolygonMiden/miden-vm/blob/ed0e87019fd1354b782cfab9bfbe5daa183a4e16/miden/tests/integration/operations/sys_ops.rs#L22) breaking.

**Comment by scottdieringer** [comment]
I no one else is working on this I would like to tackle it.

**Comment by plafer** [comment]
Go for it 🙂 Let us know if you have any questions

**Comment by scottdieringer** [comment]
Here's a PR for this issue: [PR-1194](https://github.com/0xPolygonMiden/miden-vm/pull/1194)

**Comment by bobbinth** [comment]
Closed by #1194.
