### ISSUE TITLE
`ExecutionTrace.main_trace`: change type to `MainTrace`

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1201]
> We should have `main_trace` be a `MainTrace` (and implement `AsRef<ColMatrix<Felt>>` for `MainTrace`). This is really the type that we want in the VM, and we can convert it in a `ColMatrix` for winterfell's `Trace::main_segment()`

_Originally posted by @plafer in https://github.com/0xPolygonMiden/miden-vm/pull/1140#discussion_r1445299152_

**Comment by bobbinth** [comment]
@plafer - this is now closed by #1214, right?

**Comment by plafer** [comment]
Yup!
