### ISSUE TITLE
Reproducible (ish) builds

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#1259]
Issues:

- CI uses unpinned dependencies nightly versions
- CI uses unpinned library versions
- There isn't an easy way to reproduce the CI steps locally

The points above means that it is cumbersome to reproduce the CI build

- One has to look at the CI logs to find the rustc/cargo/rustup versions to re-use
- In theory, one would need to copy each individual library version by hand to reproduce the build
- One has to read the `ci.yaml` file and copy/past the commands

Usually the steps above would be done as a last resort. But when it happens it takes a lot of time to reproduce CI issues and fix them.

This issue is on how to make the above steps more reproducible, so that it takes less effort to maintain the CI.

Discord conversation: https://discord.com/channels/893151281848406016/1148602660132487279/1211740187177001080

**Comment by bobbinth** [comment]
We should probably do something similar for other repos too (crypto, base, node, client).

**Comment by hackaugusto** [comment]
@bobbinth totally agree. I opened this issue to get feedback and document the discord conversation. Collecting any objections and/or tool preferences. If there aren't any, I can replicate the issue on all repos.

**Comment by bobbinth** [comment]
Yep - makes sense. One question: in some repos we already have Makefiles - would these be replaced with `cargo make`?

**Comment by bitwalker** [comment]
> Yep - makes sense. One question: in some repos we already have Makefiles - would these be replaced with `cargo make`?

That would be my recommendation, there's no need for both, but you _could_ have the `Makefile` have a single target that installs the `cargo-make` extension and then dispatches the requested task to `cargo make` and also prints a warning so the user knows they shouldn't be using it. Not sure of that's worth it though, a note in the dev docs seems sufficient to me.

**Comment by bobbinth** [comment]
@phklive - I think this is mostly done, right? Maybe one thing that is missing is that we should commit the `Cargo.lock` file. Could you take a look and see what's needed to close this issue?

**Comment by phklive** [comment]
> @phklive - I think this is mostly done, right? Maybe one thing that is missing is that we should commit the `Cargo.lock` file. Could you take a look and see what's needed to close this issue?

Indeed I believe that this was one of the last things standing. 

Added the needed changes to close this issue in this PR: #1415 

Once merged I believe that this issue can be closed.

**Comment by bobbinth** [comment]
Closed by #1415 and others.
