### ISSUE TITLE
Syntax to refer to a procedure's MAST root inside the VM

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#1283]
The VM now supports dynamic dispatches via the `dynexec` and `dyncall` instructions. To run these instructions one first needs the MAST root of a procedure. To make this a bit easier to use in some contexts, it is benefitial to have syntax to refer to a procedure's MAST root inside the assembly language, so the assembler would dynamically fill the value for the user.

**Comment by bitwalker** [comment]
Isn't this provided by the `procref` instruction?
