### ISSUE TITLE
Miden formatting crate

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#1284]
As mentioned in https://github.com/0xPolygonMiden/miden-vm/pull/1277/files#r1526578953, it might be good to move handling pretty-printing/formatting code into a stand-alone simple crate to avoid current duplication of formatting code across multiple crates.

**Comment by bobbinth** [comment]
Created the repo [here](https://github.com/0xPolygonMiden/miden-formatting). Thank you!

**Comment by bitwalker** [comment]
I think we can close this when both 0xPolygonMiden/miden-formatting#1 and #1277 are merged. Once the former is merged, I'll update the latter, and once the latter is merged this is all sorted.
