### ISSUE TITLE
Block hash table: don't iterate over entire trace to find `HALT`

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1344]
_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/pull/1333#discussion_r1617769942_

Probably not for this PR, but I wonder how expensive this `.find()` is. Basically, we need to iterate through the whole trace to find the first `HALT` row.

One alternative to this is to get the program hash from the last row (excluding the random rows at the end). This should be possible because because the semantics of `HALT` are such that it copies over the entire state of the VM (including the decoder registers) to the next cycle. So, program hash should be the same in the last row as in the first `HALT` row.

**Comment by sergerad** [comment]
> One alternative to this is to get the program hash from the last row (excluding the random rows at the end).

@bobbinth any guidance of how to identify and exclude those random rows at the end?

And please LMK any pages/chapters from the gitbook you recommend for this topic. Thanks!

**Comment by plafer** [comment]
There is currently only 1 random row, captured by [this constant](https://github.com/0xPolygonMiden/miden-vm/blob/fce519af44dd7482b5a8ebbf88710bb1d3f4c913/processor/src/trace/mod.rs#L32), which you can use to . Note that we inject this random row [here](https://github.com/0xPolygonMiden/miden-vm/blob/fce519af44dd7482b5a8ebbf88710bb1d3f4c913/processor/src/trace/mod.rs#L232-L236).

I didn't check to see if it makes sense in this context, but we have a method [`ExecutionTrace::last_step()`](https://github.com/0xPolygonMiden/miden-vm/blob/fce519af44dd7482b5a8ebbf88710bb1d3f4c913/processor/src/trace/mod.rs#L171) that returns the index of the last row (taking the number of random rows into account). If somehow it doesn't make sense, you can just use the `NUM_RAND_ROWS` constant directly.

Hope this helps!

**Comment by bobbinth** [comment]
Closed by #1439.
