### ISSUE TITLE
Return proper error message from the `mem_ops` in case of underflow

### ISSUE THREAD

**Issue by Fumuran** [0xPolygonMiden/miden-vm#1372]
It is possible to have subtraction with underflow in the `local_to_absolute_addr` function ([here](https://github.com/0xPolygonMiden/miden-vm/blob/ddf536cd7157053f0940d7be41998b2a6546b4c1/assembly/src/assembler/instruction/mem_ops.rs#L110)) during the calculation of the addresses for the memory operation. Proper error message should be returned if this error occurs. 

Original comment: https://github.com/0xPolygonMiden/miden-vm/issues/1371#issuecomment-2201240761

**Comment by bobbinth** [comment]
Closed by #1379.
