### ISSUE TITLE
Allow procedures with the same name to differ on the number of locals

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#1377]
When compiling the account code, one can wrap the basic wallet example. The issue is that when wrapping said code, there can be name conflicts, for example, the current code [is just an re-export](https://github.com/0xPolygonMiden/miden-base/blob/c29d1def0bca6a66115a6011df1171d836563b90/objects/src/testing/account_code.rs#L69-L72):

```
        # acct proc 0
        export.wallet::receive_asset
        # acct proc 1
        export.wallet::send_asset
```

If the above is changed to:

```
        export.send_asset  # <- note the absence of the local `.1`
            exec.wallet::send_asset
        end
```

The compilation fails with `AccountCodeAssemblerError(ConflictingNumLocals("send_asset"))` when running the following test `cargo test -- executed_transaction_account_delta`. This is a bit annoying, specially because consistently using `proc` for everything is a way of circumventing https://github.com/0xPolygonMiden/miden-vm/issues/1376

**Comment by hackaugusto** [comment]
There maybe some deeper issues with the [procedure caching code](https://github.com/0xPolygonMiden/miden-vm/blob/1698d13093c1af367de2d8491940ca9b7137d504/assembly/src/assembler/procedure_cache.rs#L80). It could be that the cache is done on a per name basis, instead of a per mast or full-path.

**Comment by bobbinth** [comment]
I believe this may already be fixed. @bitwalker - could you double-check?

**Comment by bitwalker** [comment]
Yep, this is fixed. I wrote a test to confirm, both when compiling a library and when compiling a program with the compiled library, I'll open a PR so we can have it in the suite.
