### ISSUE TITLE
Program analysis tool

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#138]
It would be cool if we had a way to analyze a given script. This would let us make informed judgements about scripts we may have in the standard library. Some interesting statistics that come to mind:

* Number of VM cycles it takes to execute the script.
* Number of program blocks in the script (for each block type).
* Number of cycles per assembly instruction. E.g., a program executed `u32add.full` operation *x* times, and this translated to *y* VM cycles.

Program analysis task list (grjte edit):
- [x] Number of VM cycles it takes to execute a program.
- [x] Number of NOOPs executed as part of a program.
- [x] Total number of cycles required to execute a particular assembly instruction and the average number of cycles per instance of that instruction.
- [x] Range Checker: Length of range-checker trace (before padding)
- [ ] Range Checker: Number of unique range-checked values [probably a nice-to-have]
- [x] Hasher: overall length of hasher trace
- [ ] Hasher: Length of hasher trace required for program hashing [might be non-trivial to get]
- [ ] Hasher: Number of rows in the hasher by hash type - e.g., 2-to-1, linear hash, Merkle path verification/update [probably a nice-to-have]
- [x] Chiplets: Number of memory accesses required.
- [x] Chiplets: Number of rows in the bitwise chiplet
- [x] Identify "long pole" of the trace (e.g., stack, range checker, chiplets)

**Comment by tohrnii** [comment]
Would love to work on this issue. So should we have a script that calculates these values for stdlib programs and a utility function which takes any arbitrary script source string and outputs these values? Should this be in a separate module or part of an existing one?

**Comment by tohrnii** [comment]
@bobbinth I added a simple script to output the total number of vm cycles it takes to execute a miden assembly script. It's a standalone package that takes source script as a file input and calls `execute_iter()` function based on your suggestion. Was the intention to have this as a separate crate only to do analysis on singular scripts or did you have something else in mind?
Thanks

**Comment by tohrnii** [comment]
The things we have currently in the program analysis tool.
- [x] Number of VM cycles it takes to execute a program.
- [x] Number of NOOPs executed as part of a program.
- [x] Total number of cycles required to execute a particular assembly instruction and the average number of cycles per instance of that instruction.

Other things that might be interesting to add to the program analysis according to @bobbinth,
- [ ] Number of range checks required.
- [ ] Number of hashes required.
- [ ] Number of memory accesses required.

**Comment by bobbinth** [comment]
We could probably go into a bit more detail for these. For example:

* Range check info:
  - Length of range-checker trace (before padding)
  - Number of unique range-checked values [probably a nice-to-have]
* Hasher info
  - Overall length of hasher trace
  - Length of hasher trace required for program hashing [might be non-trivial to get]
  - Number of rows in the hasher by hash type - e.g., 2-to-1, linear hash, Merkle path verification/update [probably a nice-to-have]

We should also add number of rows in the bitwise chiplet to the list.

Finally, would probably be nice to know which part of the trace was the "long pole" - e.g., stack, range-checker, or chiplets.

**Comment by grjte** [comment]
Great, thanks @tohrnii @bobbinth ! I updated the issue with the list. Once the current related PR #315 is updated and merged maybe we can prioritize this list (identify which things we want in the next release) and think about splitting some of these into separate issues (perhaps with a new tag)? Thoughts?

**Comment by bobbinth** [comment]
Closed by #1099 and others.
