### ISSUE TITLE
`MastForest`: Ensure that the number of nodes is less than 2^30

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1392]
The serialization format of `MastForest` introduced in #1370 implicitly assumes that the internal value of a `MastNodeId` fits in 30 bits. Hence, `MastForest` should enforce this constraint.

**Comment by sergerad** [comment]
@plafer I would like to have a crack.

I'm assuming adding `Impl TryFrom<u32> for MastNodeId {` is appropriate.

**Comment by bobbinth** [comment]
Closed by #1394. Thank you again @sergerad!
