### ISSUE TITLE
Fix `ModuleGraph` constructors

### ISSUE THREAD

**Issue by plafer** [0xPolygonMiden/miden-vm#1416]
This should be done once #1226 is closed (specifically after all 4 points in https://github.com/0xPolygonMiden/miden-vm/issues/1226#issuecomment-2225263938 are addressed)

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/pull/1401#discussion_r1692056537_

For example, we could have the following constructors:
```rust
pub fn new(kernel: Kernel, libraries: IntoIterator<Item = CompiledLibrary>) -> Self {
    todo!("implement")
}

pub fn with_kernel(kernel: Kernel) -> Self {
    todo!("implement")
}

pub fn with_libraries(libraries: IntoIterator<Item = CompiledLibrary>) -> Self {
    todo!("implement")
}
```
And `Assembler::default()` could still be used to instantiate an empty assembler (i.e., the assembler without kernel or libraries).

**Comment by bobbinth** [comment]
Ah - I forgot about this issue and created #1433. I'll close this one as the new one has a more up-to-date description of the proposed constructors.
