### ISSUE TITLE
Outdated link to fibonacci.rs example

### ISSUE THREAD

**Issue by MuhtasimTanmoy** [0xPolygonMiden/miden-vm#1578]
### Packages versions

miden-vm: v0.11.0

### Bug description

Outdated link

### How can this be reproduced?

File
- [miden/README.md#fibonacci-calculator](https://github.com/0xPolygonMiden/miden-vm/blob/main/miden/README.md#fibonacci-calculator)

Line
-  In Rust, it would look like this (this is actually a simplified version of the example in [fibonacci.rs](src/examples/src/fibonacci.rs))

The link was not found.

**Comment by plafer** [comment]
Thank you for pointing this out! Closed by #1579
