### ISSUE TITLE
Project Status Question

### ISSUE THREAD

**Issue by robinsingh1** [0xPolygonMiden/miden-vm#16]
Hi there, 

Is Miden ready to start developing on for developers or would it be advisable to wait for a later release ?  Excited about the project but just wanted to get a sense of how stable the APIs are and what release version is targeted at new developers.

Thanks so much :)

Best,

**Comment by bobbinth** [comment]
Thank you for the question! I'd say it is a bit early to start building on Miden VM yet - but it's not too early to start learning how it works.

We'll be releasing specs for the new assembly language in a week or so. The basic implementation of the VM supporting these specs will follow soon thereafter. This will provide a much more stable external interface against which we'll try to minimize breaking changes going forward.
