### ISSUE TITLE
Potential refactor of crypto operations

### ISSUE THREAD

**Issue by 0xKanekiKen** [0xPolygonMiden/miden-vm#374]
According to @bobbinth, we could make `mtree_set` a bit more efficient by changing semantics of `MRUPDATE` from:

    [V, d, i, R, NV] -> [NR, d, i, R, NV]

to

    [V, d, i, R, NV] -> [V, d, i, NR, NV]

This should shave off 3 VM cycles from `mtree_set` and get it down to 11 cycles, but:

 - It would complicate handling of constraints for this operation since we change items at odd stack positions.
 - It would make `mtree_cwm` operation quite a bit less efficient.

**Comment by bobbinth** [comment]
Superseded by #654.
