### ISSUE TITLE
Print VM cycles after CLI execution

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#442]
Consider printing also the used VM cycles after the execution of a CLI masm program.

This will provide insightful information over performance, highlighting the difference when a script is plainly expensive, or the VM needs some performance tweak.

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/432#pullrequestreview-1149981918_

**Comment by Dominik1999** [comment]
I would love to work on this

**Comment by ruuderie** [comment]
@Dominik1999 do you want to pair on this?

**Comment by Dominik1999** [comment]
Hey @ruuderie yes, sure. I created a PR that does what we want, but there are tests missing. I am unsure how to test the CLI in general, but if you have some ideas please go ahead.

**Comment by bobbinth** [comment]
Some of this was addressed in #447 - but I think we should still improve it. Specifically, we have tree different metrics which are interesting here:
* Number of cycles the program took to execute on the stack.
* Number of cycles the program requires overall (including range checker and chiplet traces).
* Overall trace length (total number of cycles rounded up to the next power of two).

Only the last one is getting printed out now - and other other two are not as trivial to get (though, I think it shouldn't be super complicated either).

In terms of how it gets printed out, I'd prefer something like this:
```
Reading program file `miden/examples/fib/fib.masm`
Compiling program... done (2 ms)
Reading input file `miden/examples/fib/fib.inputs`
Executing program with hash c8653f31a1098e1b83c5d4972ec544cac00aa784bba18b5a9db7478977d38e68... done (4 ms)
VM cycles: 2034 (stack cycles: 2034) extended to 4096 steps.
Output: [8911120806959712300]
```

**Comment by Dominik1999** [comment]
Wanted to pick this up again and re-check: Do we already log the metrics in the proving step?

This is what we log when we run `prove` with `Debug` using the logger:

```Rust
        env_logger::Builder::new()
            .format(|buf, record| writeln!(buf, "{}", record.args()))
            .filter_level(log::LevelFilter::Debug)
            .init();
```

```
Proving program with hash 78d31702eb946e1817e3c0881fcb3739562f08fbddf202de2eae241b9968ab3b...
Generated execution trace of 72 columns and 4096 steps in 4 ms
Built domain of 2^15 elements in 0 ms
Extended execution trace of 72 columns from 2^12 to 2^15 steps (8x blowup) in 23 ms
Computed execution trace commitment (Merkle tree of depth 15) in 13 ms
Built auxiliary trace segment of 9 columns and 2^12 steps in 0 ms
Extended execution trace of 9 columns from 2^12 to 2^15 steps (8x blowup) in 4 ms
Computed execution trace commitment (Merkle tree of depth 15) in 4 ms
Evaluated constraints over domain of 2^15 elements in 29 ms
Converted constraint evaluations into 8 composition polynomial columns of degree 4095 in 1 ms
Evaluated 8 composition polynomial columns over LDE domain (2^15 elements) in 2 ms
Computed constraint evaluation commitment (Merkle tree of depth 15) in 2 ms
Built DEEP composition polynomial of degree 4095 in 15 ms
Evaluated DEEP composition polynomial over LDE domain (2^15 elements) in 0 ms
Computed 4 FRI layers from composition polynomial evaluations in 1 ms
Determined 27 query positions in 0 ms
Built proof object in 0 ms
Program with hash 78d31702eb946e1817e3c0881fcb3739562f08fbddf202de2eae241b9968ab3b proven in 108 ms
```

However, I don't see a number that is not a power of two.

**Comment by bobbinth** [comment]
> Wanted to pick this up again and re-check: Do we already log the metrics in the proving step?

No, the other two metrics (number of stack cycles and total cycles not rounded to a power of two) are not printed out. We might actually need to modify some internal data structures to make these metrics easily accessible to the logger.

**Comment by Dominik1999** [comment]
OK, with grjte's help I found the correct numbers. All can be found in `finalize_trace()`

### Metric 1: Number of cycles the program took to execute on the stack: 
We will use `clk` in
https://github.com/0xPolygonMiden/miden-vm/blob/9c8af67a7768b920772b3a42d89947f7f639e089/processor/src/trace/mod.rs#L268-L271

### Metric 2: Number of cycles the program requires overall (including range checker and chiplet traces) 
We will use `max_len` in
https://github.com/0xPolygonMiden/miden-vm/blob/9c8af67a7768b920772b3a42d89947f7f639e089/processor/src/trace/mod.rs#L296-L297

**Comment by bobbinth** [comment]
Yes, these are the right places. I think the tricky question is how to refactor the code to get this values into `ExecutionTrace`. A straight-forward but not very clean approach is to put them into a struct and return it from `finalize_trace()`. Another approach is to get rid of `finalize_trace()` entirely and move the code into `new()`. Maybe there is some other better option here as well.

**Comment by vlopes11** [comment]
To double check; this is already completed, right? @bobbinth @Dominik1999

**Comment by bobbinth** [comment]
I think we don't currently have the full breakdown described [here](https://github.com/0xPolygonMiden/miden-vm/issues/442#issuecomment-1372754958).
