### ISSUE TITLE
Tracking issue: Migrate to Rescue Prime Optimized hash function

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#474]
### Goal(s) 

Switch the Miden VM's native hash function to RPO.

@grjte edit: I've added the goal and working group information, but kept the details from Bobbin's original description.

### Details

Currently, the native hash function of the VM is a non-standard variation of Rescue Prime. Besides being non-standard, it has several disadvantages which we can remedy by switching to Rescue Prime Optimized (RPO), which was designed by the original authors of Rescue/Rescue Prime. We already have a Rust implementation of RPO [here](https://github.com/0xPolygonMiden/crypto/blob/main/src/hash/rpo/mod.rs).

The main difference between Rescue Prime (in the variant that we are using) and Rescue Prime Optimized are as follows:

* **Overwrite mode**: during the absorption step, instead of adding new elements to the elements in rate portion of the state, we can just overwrite them.
* **Better padding rule**: the padding rule used in the variant of Rescue Prime is one of the things that make it non-standard. This padding rule has questionable security. The padding rule described in RPO specifications is much better.
* **No inverse MDS matrix**: because of a slightly different arrangement of operations within a round, multiplication by an inverse MDS matrix is no longer needed for evaluating AIR constraints.

To replace Rescue Prime with RPO, we'll need to:
* Update how the processor works. Specifically, the hasher chiplet but probably a few other things too (e.g., chiplet bus, decoder).
* Update AIR constraints for the affected components.

One nice thing is that these updates should actually reduce the overall complexity.

### Must have

- [x] Update how the processor works. Specifically, the hasher chiplet but probably a few other things too (e.g., chiplet bus, decoder).
- [x] Update AIR constraints for the affected components.

### Nice to have

- [ ]

## Working group:
@grjte, @al-kindi, @tohrnii 

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @grjte 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by bobbinth** [comment]
Hi @jonathanxuu! We might do another upgrade after RPO. The deciding criteria here is whether we can get something more performant than RPO (e.g., 2x - 3x improvement) while maintaining the same level of confidence in the hash function.

Overall, we hope to stabilize hash function choice by May/June of this year. Meaning, any changes beyond that would be made only if there are security concerns.

**Comment by xz-cn** [comment]
> Hi @jonathanxuu! We might do another upgrade after RPO. The deciding criteria here is whether we can get something more performant than RPO (e.g., 2x - 3x improvement) while maintaining the same level of confidence in the hash function.
> 
> Overall, we hope to stabilize hash function choice by May/June of this year. Meaning, any changes beyond that would be made only if there are security concerns.

Hi @bobbinth, we at zCloak are composing merkle trees in verifiable credentials using the Rescue Prime hash and it works ok for now. The reason we didn't use a standard hasher like SHA256 is for the fast computation time of the Rescue Prime hash in Miden. But if the hash function keeps changing, it becomes a problem for us to support existing credentials.

So do you think the May/June hasher version will be long-time supported? Or should we also check out other existing standard like SHA256 or Blake3?

**Comment by bobbinth** [comment]
Hi @xz-cn!

> So do you think the May/June hasher version will be long-time supported? Or should we also check out other existing standard like SHA256 or Blake3?

Our plan is to finalize the hash function design by this timeframe and change it only if some vulnerabilities are found. In a longer time frame (say 2 - 3 years down the road), it might make sense to change the hash function if much more performant constructions are developed.

**Comment by grjte** [comment]
Closed by #623
