### ISSUE TITLE
Warn of unused imports

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#515]
Currently the parse imports will create a map of all declared imports in the MASM file, without validating a list of available modules.

When the compilation pipeline is completed, a usage of this function would lead to a module not found error. The pipeline correctly implements the module load with a lazy approach; meaning it will load & compile as the body of the procedures requires them.

However, we end up ignoring incorrect module definitions in the source, since they might never be used (and if they are, we will correctly pop an error). One example is here

https://github.com/maticnetwork/miden/blob/268742dda05d5383e61fe0c533db00dbf8b19c27/assembly/src/tests.rs#L239-L246

We require an non-existing `std::math::u512`, and never use it. Since `u256` is in scope, then this compilation will succeed.

It would be ideal to halt the compilation with a reference to an non-existing module (used or unused), and output a warning when a valid module is unused.

**Comment by saxenism** [comment]
Is this issue open and still relevant? If yes, I would like to tackle this. Can anyone assign this to me?

@bobbinth @vlopes11

**Comment by bobbinth** [comment]
@saxenism - thank you for the interest! Yes, this is still relevant, but is probably challenging to implement at this point. The main issue is that we currently don't have a way to generate warnings in the assembler (either we fail on the first error, or compilation succeeds). So, we'd either need to error out on unused imports (which I don't think is a good idea) or refactor the assembler to support warnings (which is a bigger task than this one).

**Comment by saxenism** [comment]
Makes sense. Thanks.

**Comment by bobbinth** [comment]
Closed by #1139.
