### ISSUE TITLE
Use core Range for interval checks

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#535]
We should use [Range](https://doc.rust-lang.org/std/ops/struct.Range.html) for interval checks, given their nature to reduce chances of error for repeated checks, and will cause no overhead due to their efficient implementation

They are also idiomatic to Rust and expected in many libraries and trait implementations

_Originally posted by @vlopes11 in https://github.com/maticnetwork/miden/pull/526#discussion_r1027853113_

**Comment by amankrx** [comment]
Can I work on this issue if it's not a priority right now?

**Comment by bobbinth** [comment]
Yes, that would be awesome! I'll assign it to you.

**Comment by amankrx** [comment]
> Hi @amankrx, how is the progress going with this issue? If you need help/clarification with something, don't hesitate to ask. Thanks for the contribution!

Hey, There were a lot of places where we had to implement the Range queries. So, it took a little bit of time to check all of that. Also, my exams were going on in the meantime, so I asked about the priority for this issue initially. Nevertheless, I will put an initial draft asap.

**Comment by bobbinth** [comment]
@amankrx thank you! And take your time. One thing I want to note: the scope of this should be limited to the assembler - no need to go beyond that.

**Comment by vlopes11** [comment]
Closed by https://github.com/0xPolygonMiden/miden-vm/pull/595
