### ISSUE TITLE
Move the assertions to the beginning of function

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#537]
It is desirable to have assertions in the beginning of a function because the compiler might be able to improve its optimization, and it is more readable for the users to understand the panic conditions of a function

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/530#discussion_r1028397476_

**Comment by ef3n9r98** [comment]
Hey @vlopes11, it looks like this is the only issue in the /miden repo that hasn't been assigned to someone yet. Is there a budget for fixing this issue, and if so, how much? I know some devs who'd be interested in working on this.

**Comment by MuhtasimTanmoy** [comment]
I would like to work on this.

**Comment by bobbinth** [comment]
Thank you! It is all yours!

**Comment by MuhtasimTanmoy** [comment]
Please review PR #707

**Comment by bobbinth** [comment]
Closed by #707.
