### ISSUE TITLE
Tracking issue: Assembler improvements for v0.4

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#547]
### Goals

- Improve support for working with 3rd-party libraries.
- Tie up loose ends left from v0.3 release to improve stability, code clarity, error handling etc.

### Details

For this target we should make improvements to the module provider, enable the serialization of Miden assembly libraries, and complete the handling of interior mutability in the Assembler (for code correctness).

```[tasklist]

### Must have

- [x] #469
- [x] #552
- [x] #540
- [x] #541
- [x] #536
- [x] #550
- [x] #514
```

```[tasklist]

### Nice to have

- [ ] #537 
- [x] #535
- [ ] #515
- [ ] #551
- [x] #573
- [ ] #574
```

## Working group:
@vlopes11, @Overcastan, @bobbinth

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @vlopes11 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by grjte** [comment]
Note: we discussed a simple update for debugging support which could go into the "nice to have" list for this target

**Comment by bobbinth** [comment]
> Note: we discussed a simple update for debugging support which could go into the "nice to have" list for this target

Done!

**Comment by Dominik1999** [comment]
Note: unsure if #469 and #514 also have to be tracked in the tracking issue

**Comment by bobbinth** [comment]
Closing as all "must haves" and some "nice to haves" have been addressed.
