### ISSUE TITLE
Deserialization should not panic on invalid content

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#578]
We are expecting well-formed bytes from serialized structures. Since they are external to any crate validation, they should always be considered of adversarial nature.

Panic on input might create potential vulnerabilities for services that will provide parsing capabilities.

https://github.com/maticnetwork/miden/blob/c05eb6ab944320745f3b291cb19a4e8d46a223f9/assembly/src/parsers/serde/deserialization.rs#L69-L75

**Comment by shyba** [comment]
I was going to give it a try but this file changed drastically on `next` branch. Is this issue still valid?
