### ISSUE TITLE
Refactor assembly error

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#583]
The errors definition in assembly created a domain separation between parsing and compilation.

This is a nice thing to have, but it is also creating more complexity that might not be necessary. One example is the need to add a concrete new type to represent `LibraryError`. A library error happens when a path is invalid, and this contains partially some parsing logic (i.e. the path should not contain module delimiters and should follow some format rules), or when a module path is duplicated for a same library (that goes beyond parsing a single module).

As result, we are creating more types, and this is undesirable because maintenance might become too hard.

One proposition is to have a single error definition that will encompass all of the variants. A challenge for that is the parsing error that depends on `Token` to correctly display the relevant information to the user, while this will not be applicable to other contexts (library path resoution, serialization/deserialization, etc).

Other alternative is to maintain the domain separation between the parsing error and the remainder errors, but we might end duplicating some validation logic as the library path rules will also be subject to parse & format when we deserialize libraries from binary input (hence, we don't parse from source/str).

_Originally posted by @bobbinth in https://github.com/maticnetwork/miden/pull/579#discussion_r1039849034_

**Comment by bobbinth** [comment]
Superseded by #1431.
