### ISSUE TITLE
Suggestion for VM Native Hash Function Nomenclature 

### ISSUE THREAD

**Issue by itzmeanjan** [0xPolygonMiden/miden-vm#590]
We're currently using Rescue Prime as native hash function of the VM, for which we've an instruction `rphash`, which is simply a 2-to-1 hasher i.e. given 8 field elements as input it outputs 4 field elements. We've another instruction `rpperm` which applies rescue permutation, given the 12 field element wide state as input. 

> **Note**
Find more about cryptographic operations supported by Miden VM natively https://maticnetwork.github.io/miden/user_docs/assembly/cryptographic_operations.html 

> **Note**
Rescue Prime specification https://eprint.iacr.org/2020/1143 

Recently we had an requirement ( see https://github.com/0xPolygonMiden/examples/issues/14 ) of adding support for hashing 4 field elements using Rescue Prime ( which is 1-to-1 hasher ) and we did so in https://github.com/maticnetwork/miden/pull/576. There we name it as `rescue_prime::hash_1to1` which is a standard library module routine. We've two problems with it

- We're not very satisfied with this name
- We'd ideally like to have it as an instruction like `rphash` or `rpperm` is, but we don't *yet* have a good and compact name for it.

We're searching for a name for that instruction. @bobbinth and I agree to make it `rpmap` which should map 4 field elements to another set of 4 field elements which is the cryptographic digest produced by applying Rescue Prime hash function. We're open to other suggestions. 

---

Recently, Rescue Prime Optimized was published and that's where we want to move to, in coming weeks, from Rescue Prime. Well that calls for changing the name of VM native hasher and permuter 

What does it do ? | Now | ( *probably* ) In Future 
---| --: | --:
Given 8 field elements, it condenses them to 4 field elements | `rphash` | `rpohash`
Given 4 field elements, it condenses them to 4 field elements | `rpmap` | `rpomap`
Given 12 field elements, it permutes them using Rescue Permutation | `rpperm` | `rpoperm`

> **Note**
Rescue Prime Optimized specification https://eprint.iacr.org/2022/1577

But say in future there's another breaking change because we decide to move to `Rescue Prime Optimized *` or some other hash function, again we've to totally rename these instructions. We'd like to avoid that situation. So we propose

What does it do ? | Proposed Instruction Name | Selected Instruction Name
---| --: | --:
Given 8 field elements, it merges them into 4 field elements | `hmerge` | -
Given 4 field elements, it maps them to 4 field elements | `hmap` | -
Given 12 field elements, it permutes them using Rescue Permutation | `hperm` | -

We're looking for your opinion.

**Comment by bobbinth** [comment]
I like `hmerge` and `hperm` but `hmap` concerns me a bit. Other potential options for `hmap`:
* `hash`
* `hmix`
* `digest`

Thought, I'm not sure I like any of them better than `hmap`.

**Comment by itzmeanjan** [comment]
> Thought, I'm not sure I like any of them better than `hmap`.

Same, I like `hmap` better than all other options we've right now.

**Comment by Al-Kindi-0** [comment]
What about `happly` ? Maybe not so different from `hmap`.

**Comment by itzmeanjan** [comment]
> What about `happly` ? Maybe not so different from `hmap`.

Something which sounds different :)

**Comment by bobbinth** [comment]
How about `hone` for "hash one"? Or maybe `hoto` for "hash one-to-one"?

**Comment by itzmeanjan** [comment]
> How about `hone` for "hash one"? Or maybe `hoto` for "hash one-to-one"?

`hmap` still seems best candidate to me.

**Comment by calummoore** [comment]
The problem with having a single hash instruction (where the underlying instruction implementation could change over time), is that any change would overwrite the old hash instruction. We'd then be unable to upgrade verify any old hashes in our proofs.

**Comment by itzmeanjan** [comment]
> The problem with having a single hash instruction (where the underlying instruction implementation could change over time), is that any change would overwrite the old hash instruction. We'd then be unable to upgrade verify any old hashes in our proofs.

Yes, that's definitely a problem.

**Comment by grjte** [comment]
I believe we've settled on `hperm`, `hmerge`, and `hash` (for one-to-one hashing, instead of `hmap`)

**Comment by bobbinth** [comment]
Closed by #684 and #700
