### ISSUE TITLE
Hamming weight / pop count

### ISSUE THREAD

**Issue by matthiasgoergens** [0xPolygonMiden/miden-vm#616]
Would it be possible to add a pop count instruction that returns the number of 1s set in the binary representation of a field element?

**Comment by bobbinth** [comment]
The simplest way to do this which comes to mind is to have an assembly instruction which internally makes use of `EXPACC` operations. The main downside here is that it will be a pretty heavy instruction. Specifically, it would take about 4 cycles per bit. So, if we want to do a pop count on a value which we know is a `u32` it would take ~128 cycles, and on a full filed element it would take ~256 cycles.

**Comment by matthiasgoergens** [comment]
Thanks. What is EXPACC?

I thought of using a lookup table perhaps? Or would that be even more expansive?

**Comment by itzmeanjan** [comment]
> What is EXPACC?

It was added here https://github.com/0xPolygonMiden/miden-vm/pull/415

**Comment by bobbinth** [comment]
@bergkvist put together a much better solution in #617. This one takes roughly 35 cycles for pop count of a `u32` value. Still on the expensive side - but 4x better than what I was thinking about initially.

I do think it would be better to have this functionality in assembly instructions (rather than `stdlib`). Specifically, I'm thinking we could add 2 instructions:
- `u32checked_popcnt`
- `u32unchecked_popcnt`

**Comment by bobbinth** [comment]
Closed by #617

**Comment by matthiasgoergens** [comment]
@bobbinth You could have a lookup table with 2^8 or 2^16 elements, and use some masking and bitshifting to break your arguments into parts, look them up, and then add up their individual 'populations'. Not sure if it would be useful.

**Comment by bobbinth** [comment]
I think it could complicate things a bit - the underlying prover (Winterfell) does not support pre-computed lookup tables (though, this feature may be useful for Winterfell independently). A 2^8 table technically doesn't need to be pre-computed - but it still complicates things and in both cases, we need a native VM operation to make use of such a table.
