### ISSUE TITLE
Add support for `n=1` to move stack operations 

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#632]
The opcodes on the left are not supported (with the immediate value `1` as shown below). I suspect that is the case because the behavior exists when the opcodes on the right are used.

| opcode     | replacement         |
| ---------- | ------------------- |
| `movup.1`  | `swap` / `swap.1`   |
| `movdn.1`  | `swap` / `swap.1`   |
| `movupw.1` | `swapw` / `swapw.1` |
| `movdnw.1` | `swapw` / `swapw.1` |

While that is not a huge problem, I think it would be a bit more ergonomic to add support for the opcodes on the left.

**Comment by bobbinth** [comment]
We've been trying to avoid having instructions which do the same thing. The primary reason for this is that we want opcodes to fit into an 8-bit value - so, the max number we can have is 255. We are currently about 15 opcodes shy from this number and we'd probably want to add some more unique operations down the road.

**Comment by hackaugusto** [comment]
Can't we translate the former into the later prior to emitting MAST?

**Comment by bobbinth** [comment]
Yes, that's what'll happen at compile time, but what get serialized is assembly AST (not MAST). The overall process currently looks like this:
```
source -> AST -> MAST
```
We serialize AST (as it is more compact) but execute MAST. The 255 opcodes limitation is on the AST side (in MAST we actually have only 88 opcodes).

We could have these redundant instructions only the source code level. This way, when we parse them they get parsed into the same AST node - but I haven't thought about all pros and cons of this yet.

**Comment by hackaugusto** [comment]
Ah, thanks for the clarification! What is the motivation to limit the AST opcodes to 1byte? I suppose the MAST limitation is important to control the size of the polynomial, but I don't understand the requirement on the AST.

**Comment by bobbinth** [comment]
I'm closing this issue for the reasons explained above (i.e., we are trying to avoid having two instructions which do the same thing).
