### ISSUE TITLE
Drop the VM on the REPL on error

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#635]
# Feature request

When debugging large assemblies, identifying the instruction which caused an error and reproducing  its state is time consuming. To make this easier it would be interesting to add a flag to `run`, say `--repl-on-failure`, which would do exactly that, allowing one to inspect the VM state.

This would also work as a simple debugger, one could use `push.0 assert` as a breakpoint.

**Comment by bobbinth** [comment]
There are some thoughts about improving debugging experience here as well: https://github.com/0xPolygonMiden/miden-vm/issues/580

**Comment by hackaugusto** [comment]
@bobbinth thanks! I should have looked over the issues before creating.

If the `debug` command would have a `run` sub-command, to move the execution until the first failure, it would be even better than what I describe on this issue.

**Comment by bobbinth** [comment]
@hackaugusto - has this been addressed with the `debug` subcommand?

**Comment by hackaugusto** [comment]
I haven't tried it, but I assume one can just use the debug mode and run until end will stop on error. So should be good enough. Thansk!
