### ISSUE TITLE
Update mtree_set instruction

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#646]
Currently, the `mtree_set` instruction expects the tip of the stack to look like
```
[d, i, R, V, ...]
```
where `d` is the depth of the Merkle tree, `i` is the index of the node we want to update, `R` is the current root commitment and `V` is the value we want to update to.
After `mtree_set` is executed, the stack is left in the following configuration
```
[R', V, ...]
```
where `R'` is the new root commitment.
As part of 0xPolygonMiden/crypto/issues/37 , it would be helpful to have the execution of `mtree_set` leave the stack as
```
[V_old, R', ...]
```
where `V_old` is the value of the previous node at index `i`.

**Comment by grjte** [comment]
The `mtree_set` implementation should be updated here: https://github.com/0xPolygonMiden/miden-vm/blob/next/assembly/src/assembler/instruction/crypto_ops.rs

**Comment by grjte** [comment]
Closed by #652
