### ISSUE TITLE
Opcode to get VM's current cycle

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#647]
# Feature request

A new opcode, perhaps `clk`, with the signature `clk() -> Feld`, which transform the stack `[...] -> [clk, ...]`, where the value of `clk` is the VM's current clock cycle.

# Rationale

This instruction is useful for an operator to compute the fees of executing a few notes in the VM itself.

**Comment by 0xKanekiKen** [comment]
Closed by #663
