### ISSUE TITLE
Programatically control when the VM should stop its current execution

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#648]
# Feature request

The Miden assembly is turning complete and it is trivial to write an infinite loop with it:

```
push.1 while.true push.1 end
```

This is a problem for transactions executed by the network. An operator must be able to stop execution of the VM under some policy, for example the current number of cycles, or if a fee schedule similar to gas is implemented, once the gas is depleted.

**Comment by bobbinth** [comment]
There could be two potential ways of handling this:

1. Abort the program without generating the proof.
2. Abort the program and generate the proof that it exceeded the number of allowed cycles.

The first one should be fairly easy to implement - but may not be as useful as, for example, we won't be able to charge transaction fees for failed transactions.

The second one will require deep structural changes in the VM and is a part of a bigger problem of how to prove execution of programs which result in an error.

**Comment by hackaugusto** [comment]
This made me think, somehow we have to agree on what is the max number of cycles, because we don't want an operator to choose arbitrarily low cycles, like `1`, and have users being forced to pay for the "failed transaction". One solution is to have this at the protocol level, either as a hard constant, or use something similar to block gas limit.

But a more interesting approach would be to have arbitrary limits. As long as an operator can verify the user will pay for the computation with a conditional P2ID, there shouldn't be much of a reason not do a long computation (I'm assuming transaction execution is not done in lock step to sealing blocks, but that instead blocks are sealed with whatever proofs are available, the P2ID is not really required, just nice to have because otherwise multiple operators could work on the same long computation, and only one of them is paid, which is a lot of waste).

This makes some smart contracts easier to write, because one doesn't have to be conservative on smart contract calls that have loops (for example, the depth of Merkle trees has to be limited on Ethereum smart contracts, otherwise it is possible to grow the tree to such a size that verifying a Merkle proof wouldn't fit in a block)

**Comment by hackaugusto** [comment]
> The first one should be fairly easy to implement - but may not be as useful as, for example, we won't be able to charge transaction fees for failed transactions.

BTW, this can be useful for running the VM outside of a client. I did write an infinite loop, and on a Mac the system will handle the process gracefully, but on a Linux machine with swap usually the complete system becomes unusable. So even though it is not that useful for the rollup/clients, it can be useful for use to limit memory usage on CLI runs.

**Comment by bobbinth** [comment]
Closed by #991 and #998.
