### ISSUE TITLE
Events, LOG Opcode and Topics

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#661]
I have opened this issue to gather thoughts around the introduction of events and topics in MidenVM.

**Rationale:**
Smart contract protocols often have the requirement to communicate information to off-chain stakeholders (indexers, front-ends, users, etc).  For example an on-chain DEX would need to inform it’s stakeholders when [LP tokens have been minted / burnt, a swap has taken place and any updates to the exchange rate.](https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol#L49-L59)  This communication is typically mediated via the emission of events.  Events are data objects which encode information.  When a transaction invokes a smart contract method, [events are emitted](https://github.com/Uniswap/v2-core/blob/master/contracts/UniswapV2Pair.sol#L186) to inform off-chain clients of the impact / changes that have been applied as a consequence of the transaction.  The events are included in the transaction receipt.  In the EVM the emission of events is implemented using the [LOG* opcode](https://ethervm.io/#A0).  The LOG Opcode also optionally takes as arguments a number of “topics”.  Topics are metadata associated with events that provide additional context.  For example, a topic could be defined that specifies the user that invoked a swap on an AMM-DEX.  This would then allow the off-chain client to easily subscribe to swap events which are related to them.   This achieves a system which enables the publish-subscribe pattern.

**Resources:**
3-part series on EVM Logging: [https://coders-errand.com/logging-in-ethereum-part-1-events/](https://coders-errand.com/logging-in-ethereum-part-1-events/)
EVM LOG* Opcodes: [https://ethervm.io/#A0](https://ethervm.io/#A0)

**Comment by hackaugusto** [comment]
Here are my two cents:

I'm not sure what is the current status, but 2/3 years ago events on Ethereum clients (Geth and the now defunct Parity/OpenEthereum) had very bad performance. Even with the hierarchical 3-level bloom filters implemented on Parity. The assumption was that bloom filters would produce few false positives, which was not true in practice. So most queries degenerated to linear scans of blocks (additionally the scan required exclusive locks on the data structures). Maybe this has improved, but I would have a look at different indexing strategies / distribution methods (maybe this could be out of the vm as part of the application protocol).

Another point is that transaction hash prefix is planned to be used as a signalling method ([details](https://github.com/0xPolygonMiden/miden-base/discussions/7#discussioncomment-4489919), `Computing the prefix`). Perhaps the same method can be used. I do wonder if this method would scale to thousands of applications.

**Comment by frisitano** [comment]
I wasn't aware on the performance challenges, thanks for bringing that to light.  Do you have any resources where I can read more?

A concern with having events outside of the vm is security.  Ideally it should be possible for a light client to authenticate an event using block header information.  Do you have any ideas on how it could potentially work?

**Comment by hackaugusto** [comment]
> I wasn't aware on the performance challenges, thanks for bringing that to light. Do you have any resources where I can read more? Why and when would storage locks be required?

Unfortunately only the source code. There may be some better resources, but I'm unaware of it.

> A concern with having events outside of the vm is security. Ideally it should be possible for a light client to authenticate an event. Do you have any ideas on how it could potentially work?

The data has to come from the execution of a transaction, so an output note of sorts. But the mechanism to publish/subscribe to this can be outside of the VM.

**Comment by frisitano** [comment]
> Unfortunately only the source code. There may be some better resources, but I'm unaware of it.

Ok I'll have to take a look to see if I can find anything.  In my opinion events are a central primitive in smart contract development.  They are used commonly by devs.  Not having events may cause additional friction on-boarding devs that expect them.  Having said that, I don't think solana has events. 

> The data has to come from the execution of a transaction, so an output note of sorts. But the mechanism to publish/subscribe to this can be outside of the VM.

Yeah good point, maybe as a first pass it's probably fine to not have the log bloom and use the node client (or otherwise) to provide publish / subscribe support. One difference to notes is that events are ephemeral so we wouldn't want to persist them to state.  Maybe the virtual machine can accumulate the set of emitted events from a transactions execution in some region of reserved memory?  Then during the transaction epilogue the vm can format the events appropriately in the output / transaction receipt.  One consideration here is that transactions will be executed and proven on user devices.  As the events will be part of the output they will have to send them to the chain as part of their transaction which could increase bandwidth requirements.

**Comment by bobbinth** [comment]
I think this might be closed by #1082 and #1119. I guess the main difference is that the VM does not output any sort of a commitment to the generated events/signals. But I'm not sure if this is needed.

**Comment by bobbinth** [comment]
Closing this as we already support events. We can reopen this if we decide that events with commitments are needed.
