### ISSUE TITLE
Miden VM Tracing

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#662]
In some cases a client will need granular detail of the state of the VM as it progresses through transaction execution.  For example, a blockchain indexer which wants to provide rich insights relating to the transactions execution or alternatively for a user that needs to do some debugging.  The Miden VM should expose an interface where a client can subscribe to this granular information.  In turn the Miden Node can then expose an RPC interface where clients can request for a trace to be produced for the execution of a transaction.

Resources:
Geth Docs - https://geth.ethereum.org/docs/developers/evm-tracing/built-in-tracers
EF Talk - https://www.youtube.com/watch?v=b8RdmGsilfU&ab_channel=EthereumFoundation
Implementation Example - https://github.com/rust-blockchain/evm/blob/master/src/tracing.rs

**Comment by bobbinth** [comment]
I think we already have something like this exposed via [execute_iter()](https://github.com/0xPolygonMiden/miden-vm/blob/next/processor/src/lib.rs#L113) function. Or were you thinking of something else?

**Comment by frisitano** [comment]
Yes this is what I was looking for.  I must have missed it.

**Comment by bobbinth** [comment]
No worries! There are also thoughts in #580 on how this can be improved.
