### ISSUE TITLE
support `exec` with multiple modules on the procedures name

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#672]
The following will fail to parse:

```
begin
  exec.mod1::mod2::proc
end
```

Because currently only zero or one module can be expressed on the path, e.g. `exec.proc` and `exec.mod1::proc` are both valid. This issue is to extend the syntax and support arbitrary number of modes.

The same applies to `call` and `syscall`

**Comment by bobbinth** [comment]
This is related to #587. Maybe just add a comment to that issue instead of creating a new one?

**Comment by hackaugusto** [comment]
Ah, I didn't know about that one. Closing this as a duplicate :)
