### ISSUE TITLE
Dependency Management Pattern

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#675]
This issue is to table a discussion around how dependency management is implemented for cross-repository dependencies owned by the Miden org.  As it stands dependencies are specified using version numbers, e.g. `crypto = { package = "miden-crypto", version = "0.1.0" }`.  I recently had a situation working in the `miden-core` crate where I had a dependency on a feature in the `miden-crypto` crate which was only available in the `next` branch.

One suggestion is that we transition to using git branch dependency specification for development (and possibly releases).  Under this pattern we would specify the dependency using the git repo and branch like so `crypto = { package = "miden-crypto", git = "https://github.com/0xPolygonMiden/crypto.git", branch = "next"}`.  This means that any features merged into `next` will be immediately available.

**Comment by bobbinth** [comment]
I'm actually thinking we should just release `miden-crypto` v0.1.1 (or something like that) and then we can use it here. I don't see a lot of downsides for doing this (at least for now).

**Comment by frisitano** [comment]
Yeah I think that makes sense.  However, moving forward I think it would be better to transition to the git branch pattern.  It removes the requirement to cut releases whenever a cross-repo dependency arises.

**Comment by frisitano** [comment]
It was concluded from discussion that we will proceed to use versioning as a mean of dependency management for the foreseeable future.  If this becomes impractical (potentially as the number of cross repo dependencies increases) then we will revisit this issue and consider options.
