### ISSUE TITLE
Add hash variant to `ProofObject`

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#710]
With winterfell 5.0, the security level is defined per type. We need to extend this as arguments of the `ProofObject` so we can replicate the used properties down the stack.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/pull/708#discussion_r1113005692_

**Comment by bobbinth** [comment]
Closed by #715 and #716.
