### ISSUE TITLE
Duplicated `ProgramInfo`

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#743]
We have a duplicated struct `ProgramInfo`. This is undesirable as it might create confusion regarding its definition and references.

Core:

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/core/src/program/info.rs#L14-L18

Miden:

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/miden/src/tools/mod.rs#L55-L60

Ideally, the onde defined in `miden` should be renamed, as it will cause smaller impact than the one defined in `core`. The one in `core` is used to verify stark proofs, while the one in `miden` is used solely to provide user output.

**Comment by bobbinth** [comment]
Closed by #745.
