### ISSUE TITLE
pre-load the AdviceProvider with immutable `SimpleSMT` of all possible depth (1-64)

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#763]
As discussed in #750 there is currently no way to create a new Merkle set in the `AdviceProvider`.

The simplest way to support this would be to always pre-populate the `AdviceProvider` with immutable empty SMTs of all possible depth (1-64). Users can then use the new `mtree_clone` operation (#762) to copy the empty tree and then update it using `mtree_set`. 

In the future we will probably want to preload with the `MerkleStore` described in #89, but for now we should just prepopulate with `SimpleSMT` of depth 1-64.

The original description by @bobbinth is this:

One way to address this is to always pre-load the advice provider with immutable empty Sparse Merkle trees of all possible depth (1 - 64). That will allow users to clone empty tries of desired depth (using the clone method described above) and then add leaves to them using mtree_set instruction.

**Comment by hackaugusto** [comment]
For reference, I believe these are [the values](https://github.com/0xPolygonMiden/crypto/blob/next/src/merkle/empty_roots.rs) we need. And we may be able to have only the ones that are used in the target tiers.

**Comment by grjte** [comment]
We are now going ahead with the [`MerkleStore`](https://github.com/0xPolygonMiden/crypto/issues/89), so once that is implemented it can be preloaded as described.

**Comment by hackaugusto** [comment]
@grjte the MerkleStore has been merged and it is pre-loading the zeros:

https://github.com/0xPolygonMiden/crypto/blob/931bcc3cc3c4993ece988f84c4595d00be431184/src/merkle/store.rs#L35-L51

should we close this or is there something else to be done?

**Comment by bobbinth** [comment]
Yes - I think this one can be closed now.
