### ISSUE TITLE
Remove `codegen-units` from release

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#768]
Currently, we enforce `codegen-units` to be `1` for release mode

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/Cargo.toml#L13-L15

The default codegen-units of release mode is `16`

While the setting above is optimal for performance, it will severely impair the compilation time. This is not practical for development environments as we end up losing unnecessary time to run tasks. We currently test out bundle with release mode

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/Makefile#L4-L5

And this takes a long time due to the root workspace settings.

The specified codegen-units makes more sense for either benchmark or a special release packaging - which should be a one-time operation. If we remove this setting and introduce a new task `package` to the `Makefile` that will compile for best performance via `RUSTFLAGS`, we will have the best of both worlds. We should probably remove the `lto` setting as well.

This `Makefile` task could also contain `-C target-cpu=native` to further improve the optimization. That however needs to be used carefully as the compiled binaries would work on a subset of the target architecture (i.e. depends on the supported host CPU instructions)

**Comment by bobbinth** [comment]
Closed by #769
