### ISSUE TITLE
Advice Provider: Get node to return empty constant

### ISSUE THREAD

**Issue by vlopes11** [0xPolygonMiden/miden-vm#771]
Currently, the `mtree_get` fails if either a depth/index doesn't exist for `R`, or if `R` doesn't exist as set.

This might be misleading for scripts, as it weakly suggests the advice provider will error if such depth/index doesn't exist for the tree, and assume it exists in case there is a valid opening. However, a malicious advice provider can return an opening to an empty sub-tree constant for that depth, and make the script assume that node exists as value - when it is in fact empty. The malicious advice provider can easily convince the script of such statement since the knowledge of the opening for that depth is trivial, being just the sub-tree constant of the next depth.

Our current Merkle implementations have fixed depth. The Tiered Sparse Merkle Tree will also extend that property as each tier is of fixed depth and behaves exactly as a Sparse Merkle Tree. We might have an exception for Merkle Mountain Range that might hold variable depth depending on the size of the set, but that is to be confirmed as it could be implemented with fixed depth as well.

With that said, we should make the `mtree_get`, except for storage I/O error, infallible. It will return an empty sub-tree constant for the given depth if either the root doesn't exist, or the node doesn't exist for the set. We also need to provide the user a way to check if that value is effectively an empty sub-tree constant.

#### Advice provider

The current signature of `get_tree_node` and `get_merkle_path` already suggests such behavior and shouldn't be updated

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/processor/src/advice/mod.rs#L118

https://github.com/0xPolygonMiden/miden-vm/blob/159a04f3d4648f77d664642409e521438378bd6c/processor/src/advice/mod.rs#L128-L133

#### miden-crypto Merkle implementations

We need to update the following methods to return empty sub-tree constants as node value

- [MerkleTree::get_node](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/merkle_tree.rs#L92)
- [MerklePathSet::get_node](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/path_set.rs#L66)
- [SimpleSmt::get_node](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/simple_smt/mod.rs#L85)

And we also need to provide opening to empty sub-tree constants in case these paths are absent

- [MerkleTree::get_path](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/merkle_tree.rs#L92)
- [MerklePathSet::get_path](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/path_set.rs#L95)
- [SimpleSmt::get_path](https://github.com/0xPolygonMiden/crypto/blob/962a07292f468e872f7453f13d9df28f2a78291c/src/merkle/simple_smt/mod.rs#L105)

#### stdlib

We need to create a new module for merkle functions. One suggestion is to use `std::collections::merkle` as module path

|Procedure|Stack input|Stack output|Notes|
|---|---|---|---|
|`is_empty_node`|`[d, V, ...]`|`[e, d, V, ...]`|Set `e` to `1` if `V` is an empty sub-tree root for the depth `d`. Set `e` to `0` otherwise|

**Comment by bobbinth** [comment]
@vlopes11 - is this still relevant?

**Comment by vlopes11** [comment]
@bobbinth let's wait until the conclusion of the sparse merkle tree? I intend to have several test cases by then tackling the potential problems raised on this issue. After we have the whole structure and unblock the Kernel, I'll attempt to hijack the tree proofs with the approaches described here.
