### ISSUE TITLE
Missing docs for instructions which manipulate the advice map

### ISSUE THREAD

**Issue by bitwalker** [0xPolygonMiden/miden-vm#800]
While sitting down to write a MASM example which uses the advice provider, I noticed that the docs mention the presence of an "advice map" component of the advice provider, but there is no further mention of it elsewhere in the docs, and there are no documented instructions for interacting with it. Thankfully, @frisitano pointed me to the instructions in the assembler.

I believe the following instructions need documentation (see [here](https://github.com/0xPolygonMiden/miden-vm/blob/main/assembly/src/assembler/instruction/mod.rs#L287)):

- [ ] `adv.keyval`
- [ ] `adv.mem`

The following instructions are meant to be for internal use by higher-level instructions (per @bobbinth), but it may be worth documenting them anyway.

- [ ] `adv.u64.div`
- [ ] `adv.ext2.inv`
- [ ] `adv.ext2.intt`

**Comment by hackaugusto** [comment]
related: https://github.com/0xPolygonMiden/miden-vm/issues/673 https://github.com/0xPolygonMiden/miden-vm/issues/674

**Comment by bobbinth** [comment]
I think it would be good to look at this more holistically and come up with a good scheme of naming these instructions. Overall, we have 3 groups of instructions which interact with the advice provider:

* Group 1: moving data from the advice stack to the operand stack: `adv_push` and `adv_loadw`.
* Group 2: putting data onto the advice stack: `adv.keval`, `adv.u64div`, `adv.ext2inv`, and `adv.ext2intt`.
* Group 3: inserting data into the advice map: `adv.mem`.

I think this scheme is kind of confusing. Also, I'm anticipating that we'll have many more group 2 instructions, and maybe a few more group 3 instructions.

For group 1, we are considering renaming them into `adv_pop` and `adv_popw` as what they do is pop values from the advice stack - though I have some reservations about this (see #781).

For group 2, it would be nice to indicate somehow that the operation puts values onto the advice stack. If `adv_push` wasn't taken, we could do something like `adv_push.u64div`, `adv_push.ext2inv` etc. But maybe we can do something else?

For group 3, would be nice to indicate that this affects the advice map. Maybe it could be something like `adv_insert.mem` or `adv_map.mem`.

Curious what others thing.

**Comment by frisitano** [comment]
I think your proposal looks good @bobbinth. One suggestion that could be worthy of discussion is moving  `adv.keyval` to group three such that we have:

Group 3 - Operations for acting on the advice map:

- `adv_map.insert` - used to insert data into the advice map
- `adv_map.get` (rename of `adv.keyval`) - used to read data from the advice map to the advice stack.

**Comment by bobbinth** [comment]
I think this works. We could probably even change `adv_map.insert` to `adv_map.set` to keep it shorter and more consistent.

I think the challenging part for me is what to do with group 2 operations.

**Comment by frisitano** [comment]
> I think this works. We could probably even change `adv_map.insert` to `adv_map.set` to keep it shorter and more consistent.
> 
> I think the challenging part for me is what to do with group 2 operations.

Your proposal of freeing `adv_push` and using it for group 2 makes sense to me. Is there a reason why you don't have high conviction in this approach?

**Comment by bobbinth** [comment]
Main concern is that we lose consistency with such operations as `mem_push` and `loc_push`. The format here is `[source]_[action]` - but if we use `adv_push` to move data onto the advice stack - this is not the same pattern.

Another concern is that `adv_pop` and `adv_popw` look very similar while they actually perform different actions (i.e., `adv_pop` would push an element onto the operand stack, while `adv_popw` would overwrite top 4 elements of the operand stack).

**Comment by bobbinth** [comment]
Closed by #933.
