### ISSUE TITLE
Assembly: Introduce procedure export scope

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#822]
When developing miden assembly libraries we have three scopes we are interested in when defining a procedure:

1. module scope - procedures that should only be accessible within the module it's defined.
2. library scope - procedures that should be accessible from other modules in the same library.
3. public scope - procedures that should be accessible publicly. This defines the public api for the library.

At the minute we only have two key words for defining procedure scope - `proc` and `export`.  We need to introduce the ability to discriminate between `2.` and `3.`.  A relatively low effort solution to this would be to provide the option to add a scope argument to the `export` keyword such that the scope can be defined, e.g. `export.scope.my_proc` - scope could take the form of `pub` / `lib`.  For backward compatibility we implement it such that if the scope is not defined, `token.parts() == 2`, then the procedure is considered public.

**Comment by hackaugusto** [comment]
related https://github.com/0xPolygonMiden/miden-vm/issues/686

**Comment by bobbinth** [comment]
Yes, this could be interesting - though, might not be as straight-forward to implement.

When it comes to procedure scoping and organization, there could be another couple of things to consider may affect this issue as well.

First, we might want to support re-exports of procedures. For example:
```
use.std::foo

export.foo::bar
```
Assuming the above code is located in `std::baz` module, the user would be able to do something like:
```
use.std::baz

begin
  exec.baz::bar
end
```

Second, we don't currently support nested modules. For example, having procedures in something like `std::stark` and `std::stark::fri` is not possible because once we have module `std::stark::fri` we cannot declare module `std::stark`. It I think it would be convenient to be able to do that - maybe using similar pattern as in Rust. Specifically, the above structure could be described by two files:
```
/std/stark/mod.masm
/std/stark/fri.masm
```
Another option is to do something like this (which actually may work even now):
```
/std/stark.masm
/std/stark/fri.masm
```
But I think it looks less clean.

**Comment by bobbinth** [comment]
Some of the things discussed in this issue have already been addressed. Specifically:

- Re-exporting procedures was addressed in #940.
- "Nested" module support was added in #992.

But the points mentioned in the original issue haven't been addressed yet.

**Comment by frisitano** [comment]
I will document a proposal for implementing procedure scoping.  This proposal exclusively focuses on 

First we define additional tokens that encode the scope of the exported procedure:

assembly/src/tokens/mod.rs:
```rust
impl<'a> Token<'a> {
    // DEFINITION TOKENS
    // --------------------------------------------------------------------------------------------
    pub const BEGIN: &'static str = "begin";
    pub const CONST: &'static str = "const";
    pub const END: &'static str = "end";
    pub const EXPORT: &'static str = "export";
    pub const EXPORT_LIB: &'static str = "export(lib)";
    pub const EXPORT_MOD: &'static str = "export(mod)";
    pub const EXPORT_SUPER: &'static str = "export(super)";
    ....
    pub const PROC: &'static str = "proc";
    pub const USE: &'static str = "use";
``` 

Next we can update the `ProcedureAst` object to store the procedure scope instead of the current `is_export` bool.

```rust
pub enum ProcedureScope {
    Internal,
    Exported,
    Module,
    Super,
    Test,
    Kernel,
}


#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProcedureAst {
    pub name: ProcedureName,
    pub docs: Option<String>,
    pub num_locals: u16,
    pub body: CodeBody,
    pub start: SourceLocation,
    pub scope: ProcedureScope,
}
```

Then we modify the `ProcedureCache` to have the following structure:

```rust
#[derive(Debug)]
pub enum MaterializedProcedureScope {
    Internal(LibraryPath),
    Exported,
    Library(LibraryNamespace),
    Module(LibraryPath),
    Super(LibraryPath),
    Test,
    Kernel,
}

impl MaterializedProcedureScope {
    pub fn is_valid_invocation(&self, invocation_scope: LibraryPath) -> bool {
        ...
    }
}

pub struct SourceSet(BTreeMap<ProcedureId, MaterializedProcedureScope>);

impl SourceSet {
    pub fn is_valid_proc_id_invocation(&self, invocation_scope: LibraryPath, proc_id: ProcedureId) -> bool {
        ...
        bool
    }

    pub fn is_valid_mast_invocation(&self, invocation_scope: LibraryPath) -> bool {
        ...
        bool
    }

    pub fn insert_materialized_scope(&mut self, proc_id: ProcedureId, scope: MaterializedProcedureScope) {
        ...
    }
}

#[derive(Debug, Default)]
pub struct ProcedureCache {
    procedures: BTreeMap<RpoDigest, (Procedure, SourceSet)>,
    proc_id_map: BTreeMap<ProcedureId, RpoDigest>,
    proc_aliases: BTreeMap<ProcedureId, ProcedureId>,
}
```

We modify the `get_by_id` function to return the `SourceSet` (`pub fn get_by_id(&self, id: &ProcedureId) -> Option<&(Procedure, SourceSet)>`).

We then propagate the `SourceSet` into the `ModuleContext` when we register an external call and modify the method such that it looks like:

```rust
impl ModuleContext {
    ...

    pub fn register_external_call(
        &mut self,
        called_proc: &Procedure,
        proc_id: &Option<ProcecureId>
        source_set: SourceSet,
        inlined: bool,
    ) -> Result<(), AssemblyError> {
        // get the context of the procedure currently being compiled
        let context = self.proc_stack.last_mut().expect("no proc context");

        if let Some(proc_id) = proc_id {                                                                                                           <-- New check
            if !source_set.is_valid_proc_id_invocation(self.path, proc_id) {
            return Err(AssemblyError::invalid_proc_invocation(called_proc.name(), &self.path));  
        } else {
             if !source_set.is_valid_mast_invocation(self.path) {
             ....
             }
        }

        // append the callset of the called procedure to the current callset as all calls made as
        // the result of the called procedure may be made as a result of current procedure as well
        context.callset.append(called_proc.callset());

        // if the called procedure was not inlined, we include it in the current callset as well
        if !inlined {
            context.callset.insert(called_proc.mast_root());
        }
    }
}
```

**Comment by bobbinth** [comment]
Superseded by the discussion in https://github.com/0xPolygonMiden/miden-vm/issues/1436.
