### ISSUE TITLE
Simple program causing panic

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#832]
Using this sample program:

```
begin
  adv.keyval
end
```

Causes the VM to fail with:

```
thread 'main' panicked at 'internal error: entered unreachable code', assembly/src/assembler/span_builder.rs:154:13
```

On latest `next` commit 1de0502d087ced0bb9d7e1d754669244c7c177a7 .

**Comment by bobbinth** [comment]
Closing as in #1466 we decided to make this an error.

**Comment by plafer** [comment]
Although it would be better if the processor returned an error instead of panicking (we only added the error in the assembler).

**Comment by plafer** [comment]
It would be worth looking into what the behavior of the processor is if such a basic block is (maliciously?) constructed

**Comment by bobbinth** [comment]
> It would be worth looking into what the behavior of the processor is if such a basic block is (maliciously?) constructed

I'm not sure such a program can be currently constructed (even maliciously). To do this, we'd need to instantiate a `BasicBlockNode` with no operations, but restrict it via errors or asserts. The assert is triggered only if we use `BasicBlockNode::new_unsafe()` which itself is used during deserialization of the format which we assume to be trusted.

So, I guess it is possible to fiddle with serialization to construct a program that won't deserialize - but I think that's a separate issue.
