### ISSUE TITLE
Add decorator to push number of elements from advice map to advice stack

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#835]
Currently, we use `adv.keyval` decorator to move data from advice map to advice stack. This decorator moves just the values from the map to the stack, but if the number of values is not known, processing these values becomes difficult.

One way to address this is to introduce another decorator - something like `adv.keyvaln` (other name suggestions are welcome) which would behave similar to `adv.keyval` but would also push the number of values onto the advice stack.

**Comment by hackaugusto** [comment]
unassigned myself https://github.com/0xPolygonMiden/miden-vm/pull/834#discussion_r1163332988

**Comment by bobbinth** [comment]
Closed by #944.
