### ISSUE TITLE
Enforce Rules on Encoding of Length Metadata

### ISSUE THREAD

**Issue by itzmeanjan** [0xPolygonMiden/miden-vm#836]
Right now we rely on a manual and error-prone procedure for encoding/ decoding length metadata when serializing/ deserializing miden assembly program to binary. If not careful enough we might make mistakes such as encoding length metadata using 16 -bits, but attempting to decode length by reading 64 -bits. While working on #825 we realized we can ( and should ) improve this by standardizing some rules such as how many bytes can doc strings be of or how many number of procedures should we allow in a module or how many modules can be living in a library etc. That way when one makes such mistake we should be able to catch those during miden program compilation time. 

We keep `// TODO` notes on top of function definitions, in `miden-assembly` crate, so that we come back later and enforce such rules at construction time. @bobbinth suggested ( @ https://github.com/0xPolygonMiden/miden-vm/pull/825#pullrequestreview-1375657425 ) we create this issue so that we don't forget about it.

**Comment by bobbinth** [comment]
Closed by #838.
