### ISSUE TITLE
Improve error `ImportedProcModuleNotFound`

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#840]
This is an example for current error:

```
ImportedProcModuleNotFound(ProcedureId([76, 6, 174, 102, 136, 197, 185, 191, 0, 2, 63, 207, 185, 182, 172, 255, 235, 226, 6, 56]))
```

The `ProcedureId` is not useful to a human, so it would be useful to have the original name in there too.

Additionally it would be nice to have a levenshtein distance or something similar to propose a fix.

**Comment by bobbinth** [comment]
Closed by #1063.
