### ISSUE TITLE
Parser error message for missing parameter should include the instruction format

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#843]
This is the error for a parser error when there are missing parameters:

https://github.com/0xPolygonMiden/miden-vm/blob/4195475d75ab2d586bdb01d1ff3ea2cd626eaf7b/assembly/src/errors.rs#L229-L235

The message should include the instruction format, to aid the developer to know how many parameters are expected, how many are missing, and what are they used for.

**Comment by bobbinth** [comment]
Closed by #1062.
