### ISSUE TITLE
Mmr unpack with max peaks bound

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#845]
I wonder if we should introduce a variant of `mmr.unpack` that bounds the maximum number of peaks. This will allow the user to have an understanding of the memory requirements when allocating the `mmr_ptr`.  As it stands we cant guarantee that the peaks don't overwrite other data in memory.  This variant called be called `mmr.checked_unpack`, `mmr.bounded_unpack` or something along these lines.  Wdyt @hackaugusto / @bobbinth ?

**Comment by hackaugusto** [comment]
The current implementation is limited by how many peaks can be represented in `num_leaves`. We use a `u64` for that, so the maximum size is `65` words in total (1 for the `num_leaves`, plus the `64` possible peaks).

I think this should be made into a constant.

**Comment by frisitano** [comment]
> The current implementation is limited by how many peaks can be represented in `num_leaves`. We use a `u64` for that, so the maximum size is `65` words in total (1 for the `num_leaves`, plus the `64` possible peaks).
> 
> I think this should be made into a constant.

I see, that's good to know - thanks for explaining.

As we are using `Felt`'s to represent the `num_leaves` would it be 63 possible peaks as a `Felt` < 64 bits?

**Comment by hackaugusto** [comment]
> As we are using Felt's to represent the num_leaves would it be 63 possible peaks as a Felt < 64 bits?

Yep, I think that is correct.
