### ISSUE TITLE
Potential optimization for loading values from memory

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#86]
Currently, at the VM level we have a single [loadw](https://github.com/maticnetwork/miden/blob/next/core/src/operations/mod.rs#L297) operation which is used to load data from memory onto the stack. This operation is used as the basis for `loadw.mem` and `pushw.mem` assembly instructions. Specifically, `loadw.mem` translates directly to `loadw` operation, while `pushw.mem` pads the stack with zeros before executing `loadw`.

Thus, `loadw.mem` requires 1 VM cycle, while `popw.mem` required 6 VM cycles. We can make these a little more balanced by changing the semantics of `loadw` processor operation. Specifically, currently stack transition diagram for `loadw` looks as follows:
```
[addr, 0, 0, 0, 0, .... ] -> [a3, a2, a1, a0, ...] 
```
where, *addr* is the memory address from which to load a word, and *a0*, *a1* etc. are elements of the word located at that address. The net result is that the stack is shifted the left by one.

With the new approach we could do the following:
```
[addr, 0, 0,  .... ] -> [a3, a2, a1, a0, ...] 
```
The net result would be that the stack is shifted to the right by one.

With this approach both `loadw.mem` and `pushw.mem` instruction can be translated to 4 VM operations:
```
loadw.mem: MOVDN2 DROP DROP LOADW
pushw.mem: PAD PAD MOVUP2 LOADW
```
The net effect is that we reduce cycle count of `pushw.mem` by 2 cycles while increasing cycle count for `loadw.mem` by 3 cycles. Thus, whether this optimization is worth it should be dictated by relative prevalence of `pushw.mem` vs. `loadw.mem` in real-world programs.

**Comment by DeimosTheMisthios** [comment]
Is this something I could pick up too? The description is a bit open ended so not quite clear if it's still under consideration

**Comment by bobbinth** [comment]
@DeimosTheMisthios thank you for the interest! It is still not clear whether we should implement this - so, I'll mark this issue as "on hold" for now.

**Comment by bobbinth** [comment]
Closing this as obsolete since we no longer have `pushw.mem` instructions.
