### ISSUE TITLE
Trait for converting rust objects to advice inputs

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#864]
We often have the requirement in which we want to convert a rust object into advice inputs that can be fed into the virtual machine via the advice provider.  To achieve this we should conclude on a standardised pattern. Below I reference some proposals of how this should be implemented from @bobbinth.  Please see [here](https://github.com/0xPolygonMiden/crypto/pull/133) for the initial motivation and discussion.

> I'm not sure `IntoIterator` would be needed. One approach we could take is to have two traits: `AdviceInputs` and `ToAdviceInputs` - these traits could look as follows:
> 
> ```rust
> pub trait AdviceInputs {
>     fn push_onto_stack(&mut self, values: &[Felt]);
>     fn insert_into_map(&mut self, key: Word, values: Vec<Felt>);
>     fn add_merkle_path(&mut self, path: MerklePath);
> }
> 
> pub trait ToAdviceInputs {
>     fn to_advice_inputs<T: AdviceInputs>(&self, target: &mut T);
> }
> ```
> 
> Then, for example, we could implement `AdviceInputs` on `MemAdviceProvider` and `ToAdviceInputs` on various structs.
> 
> One drawback of the above approach is that sometimes how we reduce an object to advice inputs may be contextual - i.e., in some cases the data could go into advice map but in other cases it could go onto advice stack. The above approach wouldn't be able to handle it. But I'm not sure if that's a big deal.

> Another approach could be to have a single trait with 3 methods:
> 
> ```rust
> pub trait ToAdviceInputs {
>     fn get_stack_inputs(&self) -> Vec<Felt>;
>     fn get_map_inputs(&self) -> BTreeMap<[u8; 32], Vec<Felt>>>;
>     fn get_merkle_paths(&self) -> Vec<MerklePath>;
> }
> ```
> 
> But I'm not sure if it is better than the first approach.

**Comment by bobbinth** [comment]
After thinking a bit more about this, I still think something like the above is the right approach - but I wonder whether the VM is the right place for these traits to be defined. In my mind, a better place could be to define these traits close to where the VM is being used. In our case, maybe they should live in `miden-objects` crate. There we can implement them on relevant objects (e.g., note, account, transaction etc.) and also implement them on foreign structs (e.g., `MemAdviceProvider`, `Mmr` etc.).

But I'm open to other suggestions too.

**Comment by frisitano** [comment]
> After thinking a bit more about this, I still think something like the above is the right approach - but I wonder whether the VM is the right place for these traits to be defined. In my mind, a better place could be to define these traits close to where the VM is being used. In our case, maybe they should live in `miden-objects` crate.

This makes sense to me.

**Comment by frisitano** [comment]
I had attempted to port https://github.com/0xPolygonMiden/crypto/pull/133 to `miden-base` but was unable to do a naive port of 
`impl From<&MmrPeaks> for Vec<Felt>` to the `miden-base` crate as I received the following error:

```
only traits defined in the current crate can be implemented for types defined outside of the crate
define and implement a trait or new type instead
```

This may complicate the proposed implementation.

**Comment by hackaugusto** [comment]
@frisitano that is because of the [coherence rules](https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence).

You can wrap `Vec<Felt>` on a type on your crate. Or you can add a new crate, say `trait IntoAdviceInput` and use that instead of `From`.

**Comment by bobbinth** [comment]
Hmm, if you define `ToAdviceInputs` trait in `miden-base`, you should be able to implement it on any (even foreign type). Could you share the snippet that's not working?

**Comment by bobbinth** [comment]
Closing this as we decided to implement these traits in `miden-base`.
