### ISSUE TITLE
Paramaterize `adv.keyval` with stack position of key

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#880]
Currently `adv.keyval` loads the data associated with the top word on the stack from the `advice_map` to the `advice_stack`.  In some situations the key may not positioned at the top of the stack.  In these circumstances the developer is forced to rearange the stack to position the key at the top, this incurs a cycle cost for rearanging.  Instead we should paramaterise the `adv.keyval` instruction such that the user can specify the starting position of the key word in the stack.  e.g. to load data associated with the key word which starts at depth 5 in the stack we would execute `adv.keyval.5`.  This removes the requirement for rearanging the stack to support the load.  To support backward compatability the depth paramater should be optional and if it is not present it should be assumed that the word is at the top of the stack - `adv.keyval.0`.

**Comment by bobbinth** [comment]
I like this a lot! In general, I'd really like to refactor the instructions dealing with the advice provider. I wrote some thoughts about it in https://github.com/0xPolygonMiden/miden-vm/issues/800#issuecomment-1487522777 and https://github.com/0xPolygonMiden/miden-vm/pull/844#issuecomment-1506016096 - but so far, wasn't able to come up with a clean comprehensive approach.

**Comment by bobbinth** [comment]
Closed by #944.
