### ISSUE TITLE
Increase VM instruction slots

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#884]
First, for context, our current scheme for computing operation flags is described [here](https://0xpolygonmiden.github.io/miden-vm/design/stack/op_constraints.html). This scheme requires 8 columns: 7 for the opcode and one for degree reduction. The layout of these columns is as follows:

| $b_6$ | $b_5$ | $b_4$ | $b_3$ | $b_2$  | $b_1$ | $b_0$ | $e$  | # of ops | flag degree  |
| :---: | :---: | :---: | :---: | :----: | :---: | :---: | :----: |:-------: | :-----: |
| 0     |  x    | x     | x     | x      | x     | x     |  0     | 64       |  7      |
| 1     |  0    | x     | x     | x      | x     | -     |  0     | 16       |  6      |
| 1     |  1    | x     | x     | x      | -     | -     |  1     | 8        |  4      |

Where column $e$ is used for degree reduction and is always computed as $e = b_6 \cdot b_5$. As can be seen from above, this scheme gives us 88 operations (64 supporting degree 2 constraints, 16 supporting degree 3 constraints, and 8 supporting degree 4 constraints).

By introducing one more column for degree reduction, we could get to 96 operations. The layout for this could look as follows:

| $b_6$ | $b_5$ | $b_4$ | $b_3$ | $b_2$  | $b_1$ | $b_0$ | $e_0$ | $e_1$ | # of ops | flag degree  |
| :---: | :---: | :---: | :---: | :----: | :---: | :---: | :----: | :----: |:-------: | :-----: |
| 0     |  x    | x     | x     | x      | x     | x     |  0     |  0     | 64       |  7      |
| 1     |  0    | 0     | x     | x      | x     | -     |  0     |  0     | 8        |  6      |
| 1     |  0    | 1     | x     | x      | x     | x     |  1     |  0     | 16       |  5      |
| 1     |  1    | x     | x     | x      | -     | -     |  0     |  1     | 8        |  4      |

Where both columns $e_0$ and $e_1$ are used for degree reduction and are computed as $e_0 = b_6 \cdot b_5$ and $e_1 = b_6 \cdot (1 - b_5) \cdot b_4$. With these scheme, we'd have the following operation groups:

* 64 operations supporting max constraint degree of 2 (same as before).
* 8 operations supporting max constraint degree of 3.
* 16 operations supporting max constraint degree of 4.
* 8 operations supporting max constraint degree of 5 (same as before).

Right now, adding a single column to the trace would result in a disproportionate impact (i.e. could slow down the VM by 5% or more). The reason for this is that for maximum efficiency we want the number of columns to be divisible by 8, and adding an extra column would push us to 73 columns total. But if we figure out how to remove a a column or if it runs out that we need to go up to the next multiple of 8, adding this column could be justified.

_Originally posted by @bobbinth in https://github.com/0xPolygonMiden/miden-vm/issues/728#issuecomment-1488010960_

**Comment by bobbinth** [comment]
One way to get rid of one column is described in #395.

**Comment by bobbinth** [comment]
Closed by #887.
