### ISSUE TITLE
Add ext2exp to the instruction set

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#902]
Currently the VM supports these native operations on quadratic extensions:

- ext2add
- ext2sub
- ext2mul
- ext2div
- ext2neg
- ext2inv

Exponentiation can be computed with the above, but it would be nice to have native support.

**Comment by bobbinth** [comment]
I would actually prefer to avoid this. I'm assuming this request is motivated by the AirScript MASM backend. If so, there we should probably just have a sub-routing which translates all exponentiations to multiplications (Could even be an "optimization" pass on the IR). This shouldn't be too difficult to do as we usually deal with fairly low exponents (e.g., 7 is the highest one we have in Miden VM constraints).
