### ISSUE TITLE
Refactor `ProcedureCache` to support `get_by_hash`

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#904]
We should change `ProcedureCache` into a real struct. One reason for this is that we'd want to be able to look up procedures by two things: procedure ID and procedure MAST root.

The interface could look something like:
```Rust
impl ProcedureCache {

    pub fn insert(&mut self, proc: Procedure) {
        todo!()        
    }

    pub fn get_by_id(&self, id: ProcedureId) -> Option<&Procedure> {
        todo!()
    }

    pub fn get_by_hash(&self, root: RpoDigest) -> Option<&Procedure> {
        todo!()
    }

   pub fn contains_id(&self, id: ProcedureId) -> bool {
        todo!()
    }

    pub fn contains_hash(&self, root: RpoDigest) -> bool {
        todo!()
    }

   pub fn values(&self) -> btree_map::Values {
       todo!()
   }
}
```
This let us support `call.<MAST root>` instruction - thought, we'd probably also need to update how `Callset` works as well.

Please see #895 for more context.

**Comment by bobbinth** [comment]
Closed by #911.
