### ISSUE TITLE
Modify `CallSet` struct to support mast root call targets

### ISSUE THREAD

**Issue by frisitano-polygon** [0xPolygonMiden/miden-vm#916]
We recently made modifications to the parser and assembler to support mast root call targets.  As a follow up to this work we should make modifications to `CallSet` to support mast root call targets.  A proposal from @bobbinth was to change 

```rust
pub struct CallSet(BTreeSet<ProcedureId>);
 ```

to

```rust
pub struct CallSet(BTreeSet<RpoDigest>);
```

An alternative approach would be to introduce a new struct as follows:

```rust
pub struct CallTarget {
     ProcedureId(ProcedureId),
     MastRoot(RpoDigest)
}
```

and the modify `CallSet` as follows:

```rust
pub struct CallSet(BTreeSet<CallTarget>)
```

This would allow us to retain more contextual information - however that may not be desirable / necessary.

**Comment by bobbinth** [comment]
Closed by #1017.
