### ISSUE TITLE
Support "phantom" MAST call targets 

### ISSUE THREAD

**Issue by frisitano** [0xPolygonMiden/miden-vm#918]
We should modify the assembler to allow call targets for which we do not have the associated `CodeBlock`.  We should remove the constraint in the code below.  We should add an argument that allows the user to toggle whether phantom calls should be allowed or not. 

https://github.com/0xPolygonMiden/miden-vm/blob/0440c081d291542ba843efd65ad0e07e61574944/assembly/src/assembler/instruction/procedures.rs#L71-L76

see https://github.com/0xPolygonMiden/miden-vm/pull/911/files#r1202962206 for more context.

**Comment by bobbinth** [comment]
Closed by #1019
