### ISSUE TITLE
Inconsistent assembly errors in the assembly parser for malformed operations

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/miden-vm#93]
In ```validate_op_len``` we return ```AssemblyError::invalid_op``` when any part of the instruction is missing. Examples of this would be:
- calling ```parse_adv``` with "adv" which is missing the ```push.n``` or ```loadw``` portion
- calling ```parse_push``` with ""

In many of the parsers for the u32 operations (and possibly other places) we return ```AssemblyError::missing_param(op)``` in these cases. An example of this is calling ```parse_u32div``` with the op ""

Obviously the case with the u32 ops is trivial, but for consistency I think we should pick one error to use in all equivalent cases when the base instruction is malformed. Thoughts?

**Comment by willyrgf** [comment]
Sounds like a good idea to me. Is this still being discussed?

**Comment by bobbinth** [comment]
Closing as no longer relevant.
