### ISSUE TITLE
Handle potential duplication in random query generation

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/miden-vm#941]
The procedure generating random indices for the FRI queries as part of the recursive verifier should be generalized so that it handles potential duplicate indices.

**Comment by bobbinth** [comment]
Closing this issue as based on discussions about FRI soundness, it seems like removing duplicates is not necessary (or rather, presence of potential duplicates is already accounted for in FRI soundness analysis).
