### ISSUE TITLE
Parametrize `adv.push_mapval` instruction with constant keys

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/miden-vm#950]
Currently, `adv.push_mapval` instruction (and a variant of it `adv.push_mapvaln`) take the key for the lookup from the operand stack. It may be beneficial to create another variant of this instruction where the key is provided via a constant (see [here](https://github.com/0xPolygonMiden/miden-vm/pull/944#pullrequestreview-1487607911) for original comment).

There could be a few options for the format of this variant. For example, `adv.push_mapval_const.1.2.3.4` or maybe `adv.push_mapvalc.1.2.3.4`. We'd also want to support the ability to use this variant with a named constant - e.g., `adv.push_mapvalc.MY_KEY`.

**Comment by frisitano** [comment]
In a similar vain it could also be useful to provide the ability to specify some memory address that holds the key for the advice map.  Lets say we are processing consumed notes and we want to store the assets associated with the note in the advice map against the value of the current consumed note pointer.  We would iterate through notes using masm and on each iteration we would update the current consumed note pointer in memory.  When we call the `adv.push_mapvalm.*` instruction it would look up the value in the memory register at the address associated with the immediate value provided and push the assets from the advice map onto the stack.

```
# The memory address at which a pointer to the consumed note being executed is stored.
const.CURRENT_CONSUMED_NOTE_PTR=3

begin
...

    exec.should_process_note
    while.true
        ...
      
        # update current consumed note points
        exec.layout::set_current_consumed_note_ptr
        ...

        # Load assets onto advice stack
        adv.push_mapvalm.CURRENT_CONSUMED_NOTE_PTR
        
        ...
    end

end
```

**Comment by bobbinth** [comment]
We explored this in #1053 - but the complexity does not seem worth it. In the worst case, emulating this behavior requires 8 cycles, and I think in most situations that should be negligible.
