### ISSUE TITLE
Replace [ZERO; 4] with a constant EMPTY_WORD

### ISSUE THREAD

**Issue by tohrnii** [0xPolygonMiden/miden-vm#959]
Replace instances of `[ZERO; 4]`, `[ZERO, ZERO, ZERO, ZERO]` and `[ZERO; WORD_SIZE]` with `EMPTY_WORD`.

And replace `Felt::new(0)` with `ZERO` and `Felt::new(1)` with `ONE` wherever possible.

**Comment by ziover** [comment]
Can I work on this issue?

**Comment by tohrnii** [comment]
Thank you. That would be great! Please let me know if you have any queries.

**Comment by bobbinth** [comment]
Closed by #1059.
