### ISSUE TITLE
Add support for constants on MASM control flow

### ISSUE THREAD

**Issue by hackaugusto** [0xPolygonMiden/miden-vm#970]
To make the MASM code a little bit more maintainable in some circumstances it makes sense to support constants on control flow too, for example the `repeat` statement could use a constant to determine the number of iterations.

This is useful for situations like the recursive verifier, were we have `repeat`s depending on the number of columns in the VM. Supporting constants there would allow to have these definitions in a easier to maintain place, instead of inside the assembly code, hopefully making maintenance a bit easier.

related: https://github.com/0xPolygonMiden/miden-vm/issues/968 https://github.com/0xPolygonMiden/miden-vm/issues/766

**Comment by bobbinth** [comment]
Closed by #1124.
